In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
df = pd.read_csv("data/Dataset_insuficiencia_renal_crnica.csv")
clean_df = df.copy()

In [ ]:
clean_df = clean_df.rename(columns={
    "Identificación del paciente": "Patient_ID",
    "Edad": "Age",
    "Presión arterial": "Blood_Pressure",
    "Gravedad específica de la orina": "Specific_Gravity",
    "Albúmina en orina": "Albumin",
    "Azúcar en orina": "Sugar",
    "Glóbulos rojos": "Red_Blood_Cells",
    "Células de pus": "Pus_Cells",
    "Grupos de células de pus": "Pus_Cell_Clumps",
    "Bacterias": "Bacteria",
    "Glucosa en sangre aleatoria": "Blood_Glucose_Random",
    "Urea en sangre": "Blood_Urea",
    "Creatinina sérica": "Serum_Creatinine",
    "Sodio en sangre": "Sodium",
    "Potasio en sangre": "Potassium",
    "Hemoglobina": "Hemoglobin",
    "Volumen corpuscular empaquetado": "Packed_Cell_Volume",
    "Recuento de glóbulos blancos": "White_Blood_Cell_Count",
    "Recuento de glóbulos rojos": "Red_Blood_Cell_Count",
    "Apetito": "Appetite",
    "Insuficiencia renal crónica": "Chronic_Kidney_Disease"
})

print(clean_df.columns.tolist())

['Patient_ID', 'Age', 'Blood_Pressure', 'Specific_Gravity', 'Albumin', 'Sugar', 'Red_Blood_Cells', 'Pus_Cells', 'Pus_Cell_Clumps', 'Bacteria', 'Blood_Glucose_Random', 'Blood_Urea', 'Serum_Creatinine', 'Sodium', 'Potassium', 'Hemoglobin', 'Packed_Cell_Volume', 'White_Blood_Cell_Count', 'Red_Blood_Cell_Count', 'Appetite', 'Chronic_Kidney_Disease']

In [9]:
numeric_df = clean_df.select_dtypes(include="number")
outlier_results = []

for col in numeric_df.columns:
    Q1 = numeric_df[col].quantile(0.25)
    Q3 = numeric_df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers_count = (
        (numeric_df[col] < lower) | (numeric_df[col] > upper)
    ).sum()

    outlier_results.append({
        "Column": col,
        "Outliers Count": int(outliers_count)
    })

outlier_summary = pd.DataFrame(outlier_results)

display(outlier_summary)

                    Column  Outliers Count
0               Patient_ID               0
1                      Age             850
2           Blood_Pressure             200
3         Specific_Gravity               0
4                  Albumin               0
5                    Sugar            1809
6     Blood_Glucose_Random               0
7               Blood_Urea               4
8         Serum_Creatinine            1536
9                   Sodium              52
10               Potassium               0
11              Hemoglobin               0
12      Packed_Cell_Volume               0
13  White_Blood_Cell_Count               0
14    Red_Blood_Cell_Count               0

In [24]:
checks = {
    "Age": (2, 90),
    "Blood_Pressure": (50, 180),
    "Specific_Gravity": (1.005, 1.025),
    "Albumin": (0, 5),
    "Sugar": (0, 5),
    "Blood_Glucose_Random": (22, 490),
    "Blood_Urea": (1.5, 391),
    "Serum_Creatinine": (0.4, 76),
    "Hemoglobin": (3.1, 17.8),
    "Packed_Cell_Volume": (9, 54),
    "White_Blood_Cell_Count": (2200, 26400),
    "Red_Blood_Cell_Count": (2.1, 8)
}

for col, (low, high) in checks.items():
    if col in clean_df.columns:
        values = pd.to_numeric(clean_df[col], errors="coerce")
        mask = values.notna() & ~values.between(low, high)

        print(f"\n{col}: {mask.sum()} values outside reference dataset range")
        display(clean_df.loc[mask, [col]].head(10))

Age: 0 values outside reference dataset range

Empty DataFrame
Columns: [Age]
Index: []

Blood_Pressure: 0 values outside reference dataset range

Empty DataFrame
Columns: [Blood_Pressure]
Index: []

Specific_Gravity: 7146 values outside reference dataset range

      Specific_Gravity
7892             12.53
7893             11.36
7894             12.65
7895             11.78
7896             12.08
7897             12.14
7898             10.51
7899             14.88
7900             14.37
7901             13.81

Albumin: 7075 values outside reference dataset range

      Albumin
7892    814.1
7893    632.7
7894    307.8
7895    625.7
7896    390.0
7897    637.4
7898    506.6
7899    761.0
7900     44.1
7901    966.0

Sugar: 7146 values outside reference dataset range

      Sugar
7892    237
7893    193
7894    134
7895     72
7896     63
7897     38
7898     34
7899     50
7900     61
7901    106

Blood_Glucose_Random: 0 values outside reference dataset range

Empty DataFrame
Columns: [Blood_Glucose_Random]
Index: []

Blood_Urea: 0 values outside reference dataset range

Empty DataFrame
Columns: [Blood_Urea]
Index: []

Serum_Creatinine: 0 values outside reference dataset range

Empty DataFrame
Columns: [Serum_Creatinine]
Index: []

Hemoglobin: 0 values outside reference dataset range

Empty DataFrame
Columns: [Hemoglobin]
Index: []

Packed_Cell_Volume: 0 values outside reference dataset range

Empty DataFrame
Columns: [Packed_Cell_Volume]
Index: []

White_Blood_Cell_Count: 0 values outside reference dataset range

Empty DataFrame
Columns: [White_Blood_Cell_Count]
Index: []

Red_Blood_Cell_Count: 0 values outside reference dataset range

Empty DataFrame
Columns: [Red_Blood_Cell_Count]
Index: []

In [27]:

columns = ["Gravedad específica de la orina", "Albúmina en orina", "Azúcar en orina"  ]

for col in columns:
    values = pd.to_numeric(df[col], errors="coerce")

    print(f"\n--- {col} ---")
    print("Minimum:", values.min())
    print("Maximum:", values.max())
    print("Unique values:", values.nunique())

    print("\nMost frequent values:")
    display(values.value_counts().head(15))

--- Gravedad específica de la orina ---
Minimum: 10.0
Maximum: 1025.0
Unique values: 522

Most frequent values:

Gravedad específica de la orina
1017.00    765
1015.00    748
1023.00    707
1021.00    699
1020.00    696
1022.00    690
1024.00    686
1019.00    684
1025.00    677
1018.00    676
1016.00    653
1005.00     29
10.25       28
1013.00     27
1012.00     27
Name: count, dtype: int64

--- Albúmina en orina ---
Minimum: 0.0
Maximum: 989.9
Unique values: 5051

Most frequent values:

Albúmina en orina
1.0      3881
0.0      3816
3.0        61
4.0        53
2.0        50
5.0        50
28.0        7
129.5       6
25.8        6
16.1        6
391.2       5
211.9       5
817.9       5
379.4       5
15.4        5
Name: count, dtype: int64

--- Azúcar en orina ---
Minimum: 0
Maximum: 1000
Unique values: 959

Most frequent values:

Azúcar en orina
0      3853
1      3844
4        64
5        55
3        45
2        42
57       35
181      32
221      31
84       31
232      30
40       30
214      30
222      29
124      29
Name: count, dtype: int64

In [11]:
display(
    clean_df["Specific_Gravity"]
    .value_counts()
    .sort_index(ascending=False)
    .head(30)
)

Specific_Gravity
1025.00    677
1024.00    686
1023.00    707
1022.00    690
1021.00    699
1020.00    696
1019.00    684
1018.00    676
1017.00    765
1016.00    653
1015.00    748
1014.00     24
1013.00     27
1012.00     27
1011.00     16
1010.00     25
1009.00     22
1008.00     17
1007.00     22
1006.00     13
1005.00     29
15.00        5
14.99       10
14.98       16
14.97       13
14.96       15
14.95       13
14.94       15
14.93       11
14.92       15
Name: count, dtype: int64

In [12]:
mask = clean_df["Specific_Gravity"] >= 1000

clean_df.loc[mask, "Specific_Gravity"] = (
    clean_df.loc[mask, "Specific_Gravity"] / 1000
)

print(clean_df["Specific_Gravity"].value_counts().sort_index().head(30))

Specific_Gravity
1.005      29
1.006      13
1.007      22
1.008      17
1.009      22
1.010      25
1.011      16
1.012      27
1.013      27
1.014      24
1.015     748
1.016     653
1.017     765
1.018     676
1.019     684
1.020     696
1.021     699
1.022     690
1.023     707
1.024     686
1.025     677
10.000     11
10.010     10
10.020     18
10.030     16
10.040     11
10.050     24
10.060     18
10.070      9
10.080     15
Name: count, dtype: int64

In [13]:
col = "Specific_Gravity"

invalid_mask = (
    clean_df[col].notna()
    & ~clean_df[col].between(1.005, 1.025)
)

print("Values needing review:", invalid_mask.sum())

display(
    clean_df.loc[invalid_mask, [col]]
    .value_counts()
    .rename("Count")
    .reset_index()
)

Values needing review: 7148

     Specific_Gravity  Count
0               10.25     28
1               14.16     25
2               11.58     24
3               10.05     24
4               12.48     24
..                ...    ...
496             12.06      6
497             13.04      6
498             12.36      6
499             15.00      5
500             12.66      5

[501 rows x 2 columns]

In [19]:
clean_df = clean_df.dropna(subset=["Chronic_Kidney_Disease"]).copy()

print("shape after removing missing target values:", clean_df.shape)
print("missing target values:", clean_df["Chronic_Kidney_Disease"].isna().sum())

shape after removing missing target values: (15049, 21)
missing target values: 0

feature engineering

In [30]:
clean_df["Age_Group"] = pd.cut(
    clean_df["Age"],
    bins=[-np.inf, 18, 40, 60, np.inf],
    labels=["child", "young_adult", "middle_aged", "senior"],
    right=False
)

clean_df["Blood_Pressure_Category"] = pd.cut(
    clean_df["Blood_Pressure"],
    bins=[-np.inf, 90, 120, 140, np.inf],
    labels=["low", "normal", "elevated", "high"],
    right=False
)

clean_df["Blood_Glucose_Category"] = pd.cut(
    clean_df["Blood_Glucose_Random"],
    bins=[-np.inf, 70, 140, 200, np.inf],
    labels=["low", "normal", "elevated", "high"],
    right=False
)

print(clean_df[[
    "Age",
    "Age_Group",
    "Blood_Pressure",
    "Blood_Pressure_Category",
    "Blood_Glucose_Random",
    "Blood_Glucose_Category"
]].head())

print("shape after feature engineering:", clean_df.shape)

print(clean_df[[
    "Age_Group",
    "Blood_Pressure_Category",
    "Blood_Glucose_Category"
]].isna().sum())

   Age    Age_Group  Blood_Pressure Blood_Pressure_Category  \
0   48  middle_aged             178                    high
1    7        child             138                elevated
2   62       senior             165                    high
3   48  middle_aged             141                    high
4   51  middle_aged             175                    high

   Blood_Glucose_Random Blood_Glucose_Category
0                   298                   high
1                   187               elevated
2                   286                   high
3                   165               elevated
4                   179               elevated
shape after feature engineering: (15049, 24)
Age_Group                  0
Blood_Pressure_Category    0
Blood_Glucose_Category     0
dtype: int64

In [32]:
clean_df.to_csv("data clean/data clean.csv", index=False)