In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
df = pd.read_csv("data/Dataset_insuficiencia_renal_crnica.csv")
clean_df = df.copy()
pd.set_option("display.max_rows", None)

In [3]:
clean_df = clean_df.rename(columns={
    "Identificación del paciente": "Patient_ID",
    "Edad": "Age",
    "Presión arterial": "Blood_Pressure",
    "Gravedad específica de la orina": "Specific_Gravity",
    "Albúmina en orina": "Albumin",
    "Azúcar en orina": "Sugar",
    "Glóbulos rojos": "Red_Blood_Cells",
    "Células de pus": "Pus_Cells",
    "Grupos de células de pus": "Pus_Cell_Clumps",
    "Bacterias": "Bacteria",
    "Glucosa en sangre aleatoria": "Blood_Glucose_Random",
    "Urea en sangre": "Blood_Urea",
    "Creatinina sérica": "Serum_Creatinine",
    "Sodio en sangre": "Sodium",
    "Potasio en sangre": "Potassium",
    "Hemoglobina": "Hemoglobin",
    "Volumen corpuscular empaquetado": "Packed_Cell_Volume",
    "Recuento de glóbulos blancos": "White_Blood_Cell_Count",
    "Recuento de glóbulos rojos": "Red_Blood_Cell_Count",
    "Apetito": "Appetite",
    "Insuficiencia renal crónica": "Chronic_Kidney_Disease"
})

print(clean_df.columns.tolist())

['Patient_ID', 'Age', 'Blood_Pressure', 'Specific_Gravity', 'Albumin', 'Sugar', 'Red_Blood_Cells', 'Pus_Cells', 'Pus_Cell_Clumps', 'Bacteria', 'Blood_Glucose_Random', 'Blood_Urea', 'Serum_Creatinine', 'Sodium', 'Potassium', 'Hemoglobin', 'Packed_Cell_Volume', 'White_Blood_Cell_Count', 'Red_Blood_Cell_Count', 'Appetite', 'Chronic_Kidney_Disease']

In [4]:
numeric_df = clean_df.select_dtypes(include="number")
outlier_results = []

for col in numeric_df.columns:
    Q1 = numeric_df[col].quantile(0.25)
    Q3 = numeric_df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers_count = (
        (numeric_df[col] < lower) | (numeric_df[col] > upper)
    ).sum()

    outlier_results.append({
        "Column": col,
        "Outliers Count": int(outliers_count)
    })

outlier_summary = pd.DataFrame(outlier_results)

display(outlier_summary)

                    Column  Outliers Count
0               Patient_ID               0
1                      Age             850
2           Blood_Pressure             200
3         Specific_Gravity               0
4                  Albumin               0
5                    Sugar            1809
6     Blood_Glucose_Random               0
7               Blood_Urea               4
8         Serum_Creatinine            1536
9                   Sodium              52
10               Potassium               0
11              Hemoglobin               0
12      Packed_Cell_Volume               0
13  White_Blood_Cell_Count               0
14    Red_Blood_Cell_Count               0

In [5]:
checks = {
    "Age": (2, 90),
    "Blood_Pressure": (50, 180),
    "Specific_Gravity": (1.005, 1.025),
    "Albumin": (0, 5),
    "Sugar": (0, 5),
    "Blood_Glucose_Random": (22, 490),
    "Blood_Urea": (1.5, 391),
    "Serum_Creatinine": (0.4, 76),
    "Hemoglobin": (3.1, 17.8),
    "Packed_Cell_Volume": (9, 54),
    "White_Blood_Cell_Count": (2200, 26400),
    "Red_Blood_Cell_Count": (2.1, 8)
}

for col, (low, high) in checks.items():
    if col in clean_df.columns:
        values = pd.to_numeric(clean_df[col], errors="coerce")
        mask = values.notna() & ~values.between(low, high)

        print(f"\n{col}: {mask.sum()} values outside reference dataset range")
        display(clean_df.loc[mask, [col]].head(10))

Age: 0 values outside reference dataset range

Empty DataFrame
Columns: [Age]
Index: []

Blood_Pressure: 0 values outside reference dataset range

Empty DataFrame
Columns: [Blood_Pressure]
Index: []

Specific_Gravity: 15051 values outside reference dataset range

   Specific_Gravity
0            1010.0
1            1014.0
2            1014.0
3            1007.0
4            1015.0
5            1007.0
6            1015.0
7            1010.0
8            1009.0
9            1007.0

Albumin: 7077 values outside reference dataset range

      Albumin
7892    814.1
7893    632.7
7894    307.8
7895    625.7
7896    390.0
7897    637.4
7898    506.6
7899    761.0
7900     44.1
7901    966.0

Sugar: 7148 values outside reference dataset range

      Sugar
7892    237
7893    193
7894    134
7895     72
7896     63
7897     38
7898     34
7899     50
7900     61
7901    106

Blood_Glucose_Random: 0 values outside reference dataset range

Empty DataFrame
Columns: [Blood_Glucose_Random]
Index: []

Blood_Urea: 0 values outside reference dataset range

Empty DataFrame
Columns: [Blood_Urea]
Index: []

Serum_Creatinine: 0 values outside reference dataset range

Empty DataFrame
Columns: [Serum_Creatinine]
Index: []

Hemoglobin: 0 values outside reference dataset range

Empty DataFrame
Columns: [Hemoglobin]
Index: []

Packed_Cell_Volume: 0 values outside reference dataset range

Empty DataFrame
Columns: [Packed_Cell_Volume]
Index: []

White_Blood_Cell_Count: 0 values outside reference dataset range

Empty DataFrame
Columns: [White_Blood_Cell_Count]
Index: []

Red_Blood_Cell_Count: 0 values outside reference dataset range

Empty DataFrame
Columns: [Red_Blood_Cell_Count]
Index: []

In [6]:

columns = ["Gravedad específica de la orina", "Albúmina en orina", "Azúcar en orina"  ]

for col in columns:
    values = pd.to_numeric(df[col], errors="coerce")

    print(f"\n--- {col} ---")
    print("Minimum:", values.min())
    print("Maximum:", values.max())
    print("Unique values:", values.nunique())

    print("\nMost frequent values:")
    display(values.value_counts().head(15))

--- Gravedad específica de la orina ---
Minimum: 10.0
Maximum: 1025.0
Unique values: 522

Most frequent values:

Gravedad específica de la orina
1017.00    765
1015.00    748
1023.00    707
1021.00    699
1020.00    696
1022.00    690
1024.00    686
1019.00    684
1025.00    677
1018.00    676
1016.00    653
1005.00     29
10.25       28
1013.00     27
1012.00     27
Name: count, dtype: int64

--- Albúmina en orina ---
Minimum: 0.0
Maximum: 989.9
Unique values: 5051

Most frequent values:

Albúmina en orina
1.0      3881
0.0      3816
3.0        61
4.0        53
2.0        50
5.0        50
28.0        7
129.5       6
25.8        6
16.1        6
391.2       5
211.9       5
817.9       5
379.4       5
15.4        5
Name: count, dtype: int64

--- Azúcar en orina ---
Minimum: 0
Maximum: 1000
Unique values: 959

Most frequent values:

Azúcar en orina
0      3853
1      3844
4        64
5        55
3        45
2        42
57       35
181      32
221      31
84       31
232      30
40       30
214      30
222      29
124      29
Name: count, dtype: int64

In [7]:
display(
    clean_df["Specific_Gravity"]
    .value_counts()
    .sort_index(ascending=False)
    .head(30)
)

Specific_Gravity
1025.00    677
1024.00    686
1023.00    707
1022.00    690
1021.00    699
1020.00    696
1019.00    684
1018.00    676
1017.00    765
1016.00    653
1015.00    748
1014.00     24
1013.00     27
1012.00     27
1011.00     16
1010.00     25
1009.00     22
1008.00     17
1007.00     22
1006.00     13
1005.00     29
15.00        5
14.99       10
14.98       16
14.97       13
14.96       15
14.95       13
14.94       15
14.93       11
14.92       15
Name: count, dtype: int64

In [8]:
mask = clean_df["Specific_Gravity"] >= 1000

clean_df.loc[mask, "Specific_Gravity"] = (
    clean_df.loc[mask, "Specific_Gravity"] / 1000
)

print(clean_df["Specific_Gravity"].value_counts().sort_index().head(30))

Specific_Gravity
1.005      29
1.006      13
1.007      22
1.008      17
1.009      22
1.010      25
1.011      16
1.012      27
1.013      27
1.014      24
1.015     748
1.016     653
1.017     765
1.018     676
1.019     684
1.020     696
1.021     699
1.022     690
1.023     707
1.024     686
1.025     677
10.000     11
10.010     10
10.020     18
10.030     16
10.040     11
10.050     24
10.060     18
10.070      9
10.080     15
Name: count, dtype: int64

In [9]:
clean_df["Specific_Gravity"] = clean_df["Specific_Gravity"].clip(lower=1.005, upper=1.030)

In [10]:
clean_df = clean_df.dropna(subset=["Chronic_Kidney_Disease"]).copy()

print("shape after removing missing target values:", clean_df.shape)
print("missing target values:", clean_df["Chronic_Kidney_Disease"].isna().sum())

shape after removing missing target values: (15049, 21)
missing target values: 0

In [11]:
print(clean_df["Specific_Gravity"].describe())

count    15049.000000
mean         1.024573
std          0.005780
min          1.005000
25%          1.020000
50%          1.025000
75%          1.030000
max          1.030000
Name: Specific_Gravity, dtype: float64

Albumin

In [12]:
df = pd.read_csv("data/Dataset_insuficiencia_renal_crnica.csv")

clean_df["Albumin"] = df.loc[clean_df.index, "Albúmina en orina"]

In [13]:
clean_df.loc[clean_df["Albumin"].between(0, 5), "Albumin"]

0        2.0
1        1.0
2        2.0
3        4.0
4        4.0
5        1.0
6        2.0
7        2.0
8        1.0
9        4.0
10       1.0
11       5.0
12       1.0
13       3.0
14       5.0
15       2.0
16       4.0
17       2.0
18       2.0
19       3.0
20       3.0
21       2.0
22       3.0
23       5.0
24       3.0
25       3.0
26       5.0
27       3.0
28       4.0
29       2.0
30       5.0
31       3.0
32       4.0
33       5.0
34       4.0
35       1.0
36       1.0
37       2.0
38       4.0
39       2.0
40       5.0
41       3.0
42       3.0
43       4.0
44       1.0
45       4.0
46       1.0
47       3.0
48       4.0
49       1.0
50       3.0
51       5.0
52       3.0
53       2.0
54       4.0
55       3.0
56       4.0
57       4.0
58       3.0
59       2.0
60       4.0
61       2.0
62       1.0
63       5.0
64       5.0
65       1.0
66       5.0
67       1.0
68       1.0
69       3.0
70       1.0
71       5.0
72       3.0
73       4.0
74       2.0
75       2.0
76       5.0
77       4.0
78       5.0
79       1.0
80       3.0
81       5.0
82       4.0
83       5.0
84       2.0
85       4.0
86       3.0
87       3.0
88       1.0
89       2.0
90       1.0
91       2.0
92       4.0
93       4.0
94       1.0
95       1.0
96       5.0
97       3.0
98       4.0
99       4.0
100      3.0
101      5.0
102      3.0
103      3.0
104      5.0
105      4.0
106      4.0
107      1.0
108      1.0
109      5.0
110      2.0
111      2.0
112      2.0
113      5.0
114      5.0
115      1.0
116      3.0
117      2.0
118      5.0
119      1.0
120      4.0
121      3.0
122      3.0
123      1.0
124      4.0
125      2.0
126      4.0
127      5.0
128      1.0
129      4.0
130      5.0
131      4.0
132      5.0
133      3.0
134      1.0
135      2.0
136      5.0
137      5.0
138      5.0
139      2.0
140      2.0
141      3.0
142      2.0
143      5.0
144      5.0
145      5.0
146      1.0
147      4.0
148      4.0
149      3.0
150      2.0
151      3.0
152      5.0
153      4.0
154      3.0
155      2.0
156      3.0
157      5.0
158      1.0
159      4.0
160      1.0
161      3.0
162      4.0
163      4.0
164      2.0
165      1.0
166      1.0
167      3.0
168      3.0
169      5.0
170      1.0
171      3.0
172      1.0
173      2.0
174      5.0
175      2.0
176      5.0
177      3.0
178      1.0
179      3.0
180      1.0
181      4.0
182      3.0
183      2.0
184      3.0
185      4.0
186      1.0
187      3.0
188      4.0
189      4.0
190      4.0
191      3.0
192      4.0
193      3.0
194      4.0
195      2.0
196      3.0
197      3.0
198      4.0
199      5.0
200      1.0
201      3.0
202      3.0
203      2.0
204      1.0
205      4.0
206      3.0
207      2.0
208      3.0
209      2.0
210      5.0
211      5.0
212      2.0
213      4.0
214      2.0
215      3.0
216      5.0
217      3.0
218      5.0
219      3.0
220      4.0
221      3.0
222      5.0
223      4.0
224      2.0
225      4.0
226      2.0
227      5.0
228      4.0
229      2.0
230      3.0
231      3.0
232      3.0
233      2.0
234      3.0
235      5.0
236      5.0
237      5.0
238      3.0
239      1.0
240      1.0
241      0.0
242      1.0
243      1.0
244      0.0
245      0.0
246      1.0
247      0.0
248      0.0
249      0.0
250      1.0
251      1.0
252      1.0
253      0.0
254      0.0
255      1.0
256      0.0
257      1.0
258      0.0
259      0.0
260      1.0
261      0.0
262      0.0
263      1.0
264      0.0
265      0.0
266      1.0
267      1.0
268      0.0
269      1.0
270      0.0
271      1.0
272      0.0
273      1.0
274      1.0
275      0.0
276      0.0
277      0.0
278      1.0
279      0.0
280      0.0
281      0.0
282      1.0
283      1.0
284      1.0
285      0.0
286      0.0
287      0.0
288      1.0
289      0.0
290      0.0
291      0.0
292      0.0
293      1.0
294      0.0
295      0.0
296      0.0
297      0.0
298      0.0
299      0.0
300      1.0
301      1.0
302      0.0
303      0.0
304      1.0
305      1.0
306      0.0
307      1.0
308      0.0
309      1.0
310      0.0
311      1.0
312      0.0
313      1.0
314      0.0
315      1.0
316      0.0
317      1.0
318      0.0
319      1.0
320      1.0
321      0.0
322      1.0
323      0.0
324      1.0
325      1.0
326      1.0
327      0.0
328      1.0
329      1.0
330      0.0
331      0.0
332      1.0
333      1.0
334      0.0
335      1.0
336      1.0
337      0.0
338      1.0
339      0.0
340      0.0
341      1.0
342      0.0
343      0.0
344      1.0
345      1.0
346      0.0
347      0.0
348      0.0
349      1.0
350      0.0
351      0.0
352      1.0
353      1.0
354      0.0
355      0.0
356      1.0
357      1.0
358      0.0
359      0.0
360      0.0
361      1.0
362      0.0
363      1.0
364      0.0
365      0.0
366      1.0
367      0.0
368      0.0
369      0.0
370      1.0
371      0.0
372      1.0
373      1.0
374      1.0
375      1.0
376      1.0
377      0.0
378      0.0
379      0.0
380      0.0
381      1.0
382      1.0
383      0.0
384      1.0
385      1.0
386      1.0
387      1.0
388      0.0
389      0.0
390      0.0
391      0.0
392      1.0
393      1.0
394      1.0
395      0.0
396      1.0
397      0.0
398      1.0
399      1.0
400      0.0
401      1.0
402      0.0
403      1.0
404      0.0
405      1.0
406      1.0
407      0.0
408      0.0
409      0.0
410      1.0
411      1.0
412      0.0
413      0.0
414      1.0
415      0.0
416      0.0
417      0.0
418      1.0
419      0.0
420      1.0
421      1.0
422      0.0
423      0.0
424      1.0
425      0.0
426      0.0
427      0.0
428      0.0
429      0.0
430      1.0
431      0.0
432      1.0
433      0.0
434      0.0
435      1.0
436      1.0
437      0.0
438      0.0
439      1.0
440      0.0
441      0.0
442      0.0
443      1.0
444      0.0
445      0.0
446      0.0
447      1.0
448      0.0
449      0.0
450      1.0
451      1.0
452      0.0
453      0.0
454      1.0
455      1.0
456      1.0
457      0.0
458      0.0
459      0.0
460      0.0
461      1.0
462      1.0
463      0.0
464      0.0
465      0.0
466      0.0
467      0.0
468      1.0
469      0.0
470      1.0
471      1.0
472      1.0
473      0.0
474      0.0
475      0.0
476      0.0
477      1.0
478      1.0
479      1.0
480      1.0
481      0.0
482      1.0
483      0.0
484      0.0
485      1.0
486      1.0
487      1.0
488      0.0
489      0.0
490      1.0
491      0.0
492      0.0
493      1.0
494      1.0
495      0.0
496      1.0
497      1.0
498      0.0
499      0.0
500      1.0
501      1.0
502      1.0
503      1.0
504      1.0
505      0.0
506      0.0
507      1.0
508      1.0
509      0.0
510      1.0
511      0.0
512      1.0
513      0.0
514      0.0
515      1.0
516      0.0
517      1.0
518      1.0
519      1.0
520      1.0
521      0.0
522      1.0
523      0.0
524      0.0
525      1.0
526      1.0
527      1.0
528      1.0
529      0.0
530      0.0
531      0.0
532      1.0
533      0.0
534      1.0
535      0.0
536      0.0
537      0.0
538      1.0
539      1.0
540      0.0
541      0.0
542      0.0
543      1.0
544      0.0
545      0.0
546      0.0
547      1.0
548      0.0
549      0.0
550      0.0
551      1.0
552      1.0
553      1.0
554      1.0
555      1.0
556      1.0
557      0.0
558      0.0
559      1.0
560      1.0
561      1.0
562      0.0
563      1.0
564      0.0
565      1.0
566      0.0
567      0.0
568      0.0
569      0.0
570      0.0
571      1.0
572      1.0
573      0.0
574      0.0
575      1.0
576      0.0
577      1.0
578      0.0
579      1.0
580      0.0
581      1.0
582      1.0
583      0.0
584      0.0
585      0.0
586      1.0
587      0.0
588      1.0
589      0.0
590      0.0
591      0.0
592      0.0
593      0.0
594      1.0
595      1.0
596      0.0
597      0.0
598      0.0
599      0.0
600      1.0
601      1.0
602      0.0
603      1.0
604      1.0
605      1.0
606      0.0
607      1.0
608      0.0
609      0.0
610      0.0
611      1.0
612      0.0
613      0.0
614      1.0
615      1.0
616      0.0
617      0.0
618      1.0
619      1.0
620      1.0
621      1.0
622      1.0
623      0.0
624      0.0
625      1.0
626      1.0
627      1.0
628      1.0
629      1.0
630      1.0
631      0.0
632      0.0
633      1.0
634      1.0
635      1.0
636      1.0
637      1.0
638      1.0
639      1.0
640      1.0
641      1.0
642      0.0
643      0.0
644      0.0
645      0.0
646      0.0
647      0.0
648      0.0
649      1.0
650      0.0
651      1.0
652      1.0
653      0.0
654      1.0
655      1.0
656      0.0
657      1.0
658      1.0
659      1.0
660      1.0
661      1.0
662      0.0
663      0.0
664      1.0
665      1.0
666      0.0
667      0.0
668      0.0
669      1.0
670      0.0
671      1.0
672      0.0
673      0.0
674      1.0
675      1.0
676      1.0
677      1.0
678      0.0
679      1.0
680      0.0
681      1.0
682      0.0
683      1.0
684      1.0
685      0.0
686      1.0
687      0.0
688      1.0
689      1.0
690      0.0
691      0.0
692      1.0
693      0.0
694      0.0
695      0.0
696      0.0
697      0.0
698      0.0
699      1.0
700      1.0
701      0.0
702      0.0
703      0.0
704      0.0
705      1.0
706      0.0
707      0.0
708      1.0
709      0.0
710      1.0
711      0.0
712      0.0
713      0.0
714      1.0
715      0.0
716      0.0
717      1.0
718      1.0
719      1.0
720      0.0
721      0.0
722      0.0
723      1.0
724      1.0
725      0.0
726      0.0
727      1.0
728      1.0
729      0.0
730      1.0
731      1.0
732      1.0
733      1.0
734      0.0
735      0.0
736      0.0
737      1.0
738      0.0
739      1.0
740      0.0
741      0.0
742      1.0
743      0.0
744      0.0
745      1.0
746      1.0
747      0.0
748      0.0
749      1.0
750      1.0
751      0.0
752      0.0
753      0.0
754      1.0
755      0.0
756      0.0
757      0.0
758      1.0
759      1.0
760      1.0
761      1.0
762      0.0
763      0.0
764      1.0
765      1.0
766      0.0
767      0.0
768      0.0
769      1.0
770      0.0
771      0.0
772      0.0
773      0.0
774      0.0
775      0.0
776      0.0
777      0.0
778      0.0
779      0.0
780      0.0
781      1.0
782      1.0
783      0.0
784      0.0
785      1.0
786      0.0
787      0.0
788      1.0
789      1.0
790      1.0
791      0.0
792      0.0
793      1.0
794      1.0
795      0.0
796      0.0
797      1.0
798      1.0
799      1.0
800      1.0
801      1.0
802      0.0
803      1.0
804      0.0
805      1.0
806      0.0
807      1.0
808      1.0
809      0.0
810      0.0
811      1.0
812      0.0
813      0.0
814      1.0
815      0.0
816      0.0
817      1.0
818      0.0
819      0.0
820      0.0
821      0.0
822      0.0
823      0.0
824      0.0
825      1.0
826      0.0
827      0.0
828      0.0
829      0.0
830      1.0
831      0.0
832      0.0
833      0.0
834      1.0
835      1.0
836      0.0
837      1.0
838      0.0
839      0.0
840      0.0
841      0.0
842      0.0
843      1.0
844      1.0
845      0.0
846      0.0
847      1.0
848      0.0
849      0.0
850      0.0
851      0.0
852      1.0
853      0.0
854      1.0
855      1.0
856      0.0
857      0.0
858      0.0
859      1.0
860      0.0
861      1.0
862      0.0
863      0.0
864      0.0
865      1.0
866      1.0
867      0.0
868      1.0
869      0.0
870      0.0
871      1.0
872      1.0
873      1.0
874      1.0
875      0.0
876      0.0
877      0.0
878      1.0
879      0.0
880      0.0
881      1.0
882      1.0
883      1.0
884      0.0
885      1.0
886      1.0
887      0.0
888      1.0
889      1.0
890      0.0
891      1.0
892      0.0
893      0.0
894      1.0
895      0.0
896      1.0
897      1.0
898      0.0
899      1.0
900      0.0
901      0.0
902      0.0
903      1.0
904      1.0
905      1.0
906      0.0
907      0.0
908      0.0
909      0.0
910      1.0
911      0.0
912      0.0
913      0.0
914      1.0
915      0.0
916      1.0
917      0.0
918      0.0
919      0.0
920      0.0
921      1.0
922      1.0
923      0.0
924      0.0
925      0.0
926      0.0
927      1.0
928      1.0
929      1.0
930      0.0
931      1.0
932      0.0
933      1.0
934      1.0
935      1.0
936      0.0
937      1.0
938      0.0
939      1.0
940      1.0
941      0.0
942      1.0
943      1.0
944      0.0
945      0.0
946      0.0
947      1.0
948      1.0
949      0.0
950      1.0
951      0.0
952      0.0
953      1.0
954      1.0
955      1.0
956      1.0
957      1.0
958      1.0
959      0.0
960      1.0
961      1.0
962      1.0
963      0.0
964      0.0
965      1.0
966      0.0
967      1.0
968      1.0
969      1.0
970      1.0
971      1.0
972      0.0
973      0.0
974      0.0
975      0.0
976      0.0
977      0.0
978      0.0
979      0.0
980      0.0
981      0.0
982      1.0
983      0.0
984      0.0
985      1.0
986      1.0
987      0.0
988      1.0
989      0.0
990      1.0
991      0.0
992      1.0
993      1.0
994      1.0
995      0.0
996      0.0
997      1.0
998      0.0
999      1.0
1000     0.0
1001     0.0
1002     1.0
1003     1.0
1004     0.0
1005     1.0
1006     0.0
1007     1.0
1008     0.0
1009     0.0
1010     1.0
1011     1.0
1012     1.0
1013     0.0
1014     1.0
1015     0.0
1016     1.0
1017     0.0
1018     1.0
1019     0.0
1020     0.0
1021     1.0
1022     0.0
1023     1.0
1024     1.0
1025     0.0
1026     0.0
1027     0.0
1028     0.0
1029     1.0
1030     0.0
1031     0.0
1032     1.0
1033     0.0
1034     1.0
1035     1.0
1036     0.0
1037     0.0
1038     1.0
1039     1.0
1040     1.0
1041     0.0
1042     1.0
1043     0.0
1044     1.0
1045     1.0
1046     1.0
1047     1.0
1048     0.0
1049     0.0
1050     0.0
1051     0.0
1052     0.0
1053     0.0
1054     1.0
1055     0.0
1056     0.0
1057     0.0
1058     0.0
1059     0.0
1060     1.0
1061     1.0
1062     1.0
1063     0.0
1064     0.0
1065     1.0
1066     1.0
1067     0.0
1068     0.0
1069     0.0
1070     1.0
1071     0.0
1072     0.0
1073     1.0
1074     0.0
1075     0.0
1076     0.0
1077     0.0
1078     0.0
1079     0.0
1080     0.0
1081     1.0
1082     1.0
1083     0.0
1084     0.0
1085     0.0
1086     0.0
1087     1.0
1088     0.0
1089     1.0
1090     1.0
1091     1.0
1092     1.0
1093     1.0
1094     0.0
1095     1.0
1096     1.0
1097     0.0
1098     0.0
1099     1.0
1100     0.0
1101     0.0
1102     0.0
1103     0.0
1104     1.0
1105     0.0
1106     1.0
1107     0.0
1108     0.0
1109     0.0
1110     0.0
1111     0.0
1112     0.0
1113     0.0
1114     0.0
1115     0.0
1116     1.0
1117     1.0
1118     0.0
1119     1.0
1120     0.0
1121     0.0
1122     1.0
1123     1.0
1124     0.0
1125     1.0
1126     0.0
1127     0.0
1128     0.0
1129     1.0
1130     0.0
1131     1.0
1132     1.0
1133     1.0
1134     0.0
1135     1.0
1136     0.0
1137     1.0
1138     0.0
1139     0.0
1140     0.0
1141     0.0
1142     1.0
1143     1.0
1144     1.0
1145     0.0
1146     0.0
1147     1.0
1148     0.0
1149     0.0
1150     0.0
1151     0.0
1152     1.0
1153     0.0
1154     1.0
1155     1.0
1156     1.0
1157     0.0
1158     1.0
1159     1.0
1160     1.0
1161     0.0
1162     0.0
1163     0.0
1164     0.0
1165     1.0
1166     1.0
1167     0.0
1168     0.0
1169     0.0
1170     1.0
1171     0.0
1172     0.0
1173     1.0
1174     0.0
1175     1.0
1176     1.0
1177     1.0
1178     0.0
1179     1.0
1180     0.0
1181     1.0
1182     0.0
1183     1.0
1184     1.0
1185     1.0
1186     0.0
1187     0.0
1188     0.0
1189     1.0
1190     0.0
1191     0.0
1192     0.0
1193     1.0
1194     0.0
1195     1.0
1196     1.0
1197     1.0
1198     1.0
1199     1.0
1200     0.0
1201     0.0
1202     1.0
1203     0.0
1204     1.0
1205     0.0
1206     0.0
1207     1.0
1208     0.0
1209     1.0
1210     1.0
1211     0.0
1212     1.0
1213     0.0
1214     1.0
1215     0.0
1216     0.0
1217     0.0
1218     0.0
1219     1.0
1220     1.0
1221     1.0
1222     0.0
1223     0.0
1224     0.0
1225     0.0
1226     0.0
1227     0.0
1228     1.0
1229     0.0
1230     1.0
1231     0.0
1232     1.0
1233     0.0
1234     0.0
1235     1.0
1236     0.0
1237     1.0
1238     1.0
1239     0.0
1240     1.0
1241     0.0
1242     1.0
1243     1.0
1244     1.0
1245     1.0
1246     0.0
1247     1.0
1248     1.0
1249     1.0
1250     0.0
1251     0.0
1252     1.0
1253     1.0
1254     0.0
1255     0.0
1256     1.0
1257     0.0
1258     1.0
1259     1.0
1260     1.0
1261     1.0
1262     0.0
1263     1.0
1264     0.0
1265     1.0
1266     0.0
1267     0.0
1268     1.0
1269     0.0
1270     0.0
1271     1.0
1272     0.0
1273     0.0
1274     0.0
1275     1.0
1276     0.0
1277     0.0
1278     1.0
1279     1.0
1280     1.0
1281     0.0
1282     0.0
1283     0.0
1284     1.0
1285     0.0
1286     1.0
1287     0.0
1288     0.0
1289     0.0
1290     0.0
1291     0.0
1292     1.0
1293     1.0
1294     0.0
1295     1.0
1296     1.0
1297     0.0
1298     1.0
1299     1.0
1300     1.0
1301     1.0
1302     1.0
1303     0.0
1304     0.0
1305     1.0
1306     0.0
1307     1.0
1308     0.0
1309     1.0
1310     1.0
1311     1.0
1312     0.0
1313     1.0
1314     0.0
1315     0.0
1316     1.0
1317     1.0
1318     1.0
1319     1.0
1320     1.0
1321     0.0
1322     0.0
1323     1.0
1324     1.0
1325     1.0
1326     1.0
1327     1.0
1328     0.0
1329     1.0
1330     0.0
1331     0.0
1332     1.0
1333     1.0
1334     0.0
1335     0.0
1336     0.0
1337     0.0
1338     1.0
1339     0.0
1340     0.0
1341     1.0
1342     1.0
1343     1.0
1344     0.0
1345     0.0
1346     1.0
1347     0.0
1348     1.0
1349     1.0
1350     0.0
1351     0.0
1352     0.0
1353     0.0
1354     0.0
1355     0.0
1356     0.0
1357     0.0
1358     0.0
1359     1.0
1360     0.0
1361     0.0
1362     1.0
1363     1.0
1364     1.0
1365     0.0
1366     0.0
1367     0.0
1368     0.0
1369     0.0
1370     0.0
1371     1.0
1372     0.0
1373     0.0
1374     0.0
1375     1.0
1376     1.0
1377     1.0
1378     1.0
1379     1.0
1380     1.0
1381     1.0
1382     0.0
1383     1.0
1384     0.0
1385     1.0
1386     1.0
1387     1.0
1388     1.0
1389     0.0
1390     0.0
1391     1.0
1392     0.0
1393     0.0
1394     1.0
1395     1.0
1396     0.0
1397     1.0
1398     1.0
1399     1.0
1400     1.0
1401     0.0
1402     1.0
1403     1.0
1404     1.0
1405     1.0
1406     1.0
1407     0.0
1408     1.0
1409     1.0
1410     1.0
1411     1.0
1412     1.0
1413     0.0
1414     0.0
1415     0.0
1416     1.0
1417     1.0
1418     0.0
1419     1.0
1420     1.0
1421     0.0
1422     0.0
1423     0.0
1424     1.0
1425     1.0
1426     0.0
1427     1.0
1428     0.0
1429     1.0
1430     1.0
1431     1.0
1432     1.0
1433     1.0
1434     0.0
1435     1.0
1436     0.0
1437     1.0
1438     0.0
1439     1.0
1440     0.0
1441     0.0
1442     1.0
1443     1.0
1444     1.0
1445     0.0
1446     0.0
1447     0.0
1448     1.0
1449     0.0
1450     0.0
1451     0.0
1452     0.0
1453     0.0
1454     1.0
1455     0.0
1456     1.0
1457     1.0
1458     0.0
1459     1.0
1460     0.0
1461     0.0
1462     0.0
1463     0.0
1464     0.0
1465     0.0
1466     0.0
1467     0.0
1468     0.0
1469     1.0
1470     1.0
1471     0.0
1472     0.0
1473     0.0
1474     0.0
1475     1.0
1476     0.0
1477     0.0
1478     0.0
1479     0.0
1480     0.0
1481     0.0
1482     1.0
1483     0.0
1484     1.0
1485     1.0
1486     1.0
1487     1.0
1488     1.0
1489     0.0
1490     1.0
1491     1.0
1492     0.0
1493     1.0
1494     1.0
1495     1.0
1496     1.0
1497     0.0
1498     0.0
1499     0.0
1500     0.0
1501     0.0
1502     1.0
1503     1.0
1504     1.0
1505     1.0
1506     1.0
1507     0.0
1508     0.0
1509     1.0
1510     1.0
1511     0.0
1512     1.0
1513     0.0
1514     0.0
1515     0.0
1516     1.0
1517     1.0
1518     0.0
1519     1.0
1520     1.0
1521     0.0
1522     1.0
1523     0.0
1524     1.0
1525     0.0
1526     0.0
1527     1.0
1528     0.0
1529     0.0
1530     0.0
1531     1.0
1532     1.0
1533     1.0
1534     0.0
1535     0.0
1536     1.0
1537     0.0

In [14]:
clean_df.loc[~clean_df["Albumin"].between(0, 5), "Albumin"]

7892     814.1
7893     632.7
7894     307.8
7895     625.7
7896     390.0
7897     637.4
7898     506.6
7899     761.0
7900      44.1
7901     966.0
7902      97.9
7903     278.7
7904      67.8
7905     538.5
7906      94.5
7907     954.3
7908     108.6
7909     496.6
7910     127.6
7911     892.3
7912     237.7
7913     105.1
7914     931.1
7915     908.3
7916     865.6
7917     280.4
7918     559.0
7919     559.3
7920     323.2
7921     140.8
7922     103.5
7923     670.3
7924     277.6
7925      89.2
7926     886.7
7927     485.9
7928     306.8
7929     726.3
7930     593.1
7931     605.8
7932     172.5
7933     546.5
7934     823.1
7935     905.1
7936     260.7
7937     750.2
7938      35.9
7939     459.4
7940     703.1
7941     377.4
7942     922.0
7943     591.1
7944     610.9
7945     966.8
7946     882.1
7947     841.3
7948     716.4
7949     362.1
7950     175.7
7951     131.6
7952     426.9
7953     935.3
7954     419.4
7955     138.0
7956     688.3
7957     440.5
7958     606.0
7959      44.4
7960     276.5
7961     715.2
7962     868.3
7963     404.8
7964     424.5
7965     473.9
7966     102.6
7967     844.2
7968     154.6
7969     416.4
7970     823.2
7971     126.6
7972     212.1
7973     882.3
7974     333.7
7975     465.8
7976     850.2
7977     969.9
7978     227.1
7979     131.9
7980     159.5
7981     131.6
7982     989.9
7983     449.5
7984     572.6
7985     526.3
7986     533.6
7987     409.5
7988      37.0
7989     488.1
7990     873.3
7991     338.2
7992     669.5
7993     760.7
7994      99.3
7995     208.5
7996      26.7
7997     982.2
7998     927.0
7999     907.0
8000     348.6
8001     360.8
8002     889.2
8003     623.9
8004     403.2
8005     245.6
8006      67.5
8007     753.7
8008     145.2
8009     873.1
8010     608.7
8011     650.4
8012     414.7
8013     214.3
8014     544.6
8015     194.1
8016     910.6
8017     490.4
8018     557.4
8019     745.7
8020     617.0
8021     752.9
8022     116.9
8023     752.8
8024     449.2
8025     981.2
8026     481.8
8027     220.1
8028     413.9
8029     167.6
8030     770.2
8031     300.2
8032     608.9
8033      32.8
8034      23.5
8035     555.6
8036     460.4
8037     249.1
8038     165.7
8039     905.6
8040     643.1
8041     736.7
8042     956.8
8043     147.5
8044     518.5
8045     883.9
8046      98.6
8047     560.2
8048     907.4
8049     651.8
8050     116.3
8051     910.9
8052     308.8
8053     726.2
8054     635.6
8055     117.9
8056     336.8
8057     980.7
8058     921.5
8059     161.2
8060     948.8
8061     824.8
8062     956.7
8063     478.1
8064      24.8
8065     591.0
8066     867.3
8067     853.1
8068     315.2
8069     250.2
8070     417.8
8071     899.3
8072     259.5
8073     117.5
8074     264.1
8075      45.4
8076     603.9
8077     952.8
8078     417.6
8079      67.0
8080     506.3
8081     865.7
8082     873.5
8083     159.2
8084     712.0
8085     352.6
8086     462.0
8087     258.4
8088     304.9
8089     934.2
8090     696.8
8091     815.2
8092     755.1
8093     713.5
8094     917.0
8095     796.6
8096     770.6
8097     593.9
8098     586.0
8099     101.2
8100     531.4
8101     749.5
8102     193.9
8103     622.1
8104     466.1
8105     746.0
8106     391.0
8107     311.5
8108     866.3
8109      44.3
8110     762.3
8111     814.0
8112     421.2
8113     894.1
8114     399.1
8115     394.6
8116     318.8
8117     439.7
8118     264.9
8119     989.4
8120     473.8
8121     488.0
8122     248.2
8123     865.2
8124     524.3
8125     391.2
8126     841.0
8127     616.5
8128     451.8
8129     458.7
8130     789.4
8131     652.3
8132     906.1
8133     658.6
8134     801.3
8135     982.9
8136     850.2
8137     174.7
8138     928.2
8139     235.6
8140     642.3
8141     400.6
8142     365.8
8143     401.7
8144     905.5
8145     600.1
8146     565.7
8147     573.6
8148     331.7
8149      43.9
8150     139.4
8151     646.3
8152     889.6
8153     385.6
8154     595.6
8155     300.3
8156     750.3
8157     892.3
8158     793.3
8159     929.8
8160     776.7
8161     956.0
8162     476.6
8163     437.8
8164     699.4
8165     132.4
8166     907.9
8167     770.2
8168     476.6
8169     147.8
8170     733.4
8171     385.7
8172      22.9
8173     473.3
8174     346.9
8175     112.3
8176     149.6
8177     421.7
8178     115.2
8179     840.2
8180     344.2
8181     906.8
8182     133.4
8183     875.8
8184     249.6
8185     865.4
8186     829.4
8187     855.8
8188     147.0
8189     582.9
8190     852.0
8191     616.1
8192     364.8
8193     338.6
8194     310.4
8195     482.4
8196     542.8
8197     752.3
8198     631.1
8199     388.0
8200     522.7
8201     524.6
8202     909.2
8203     894.2
8204      94.8
8205     713.0
8206      83.2
8207     136.0
8208     316.9
8209     552.6
8210     143.9
8211     125.6
8212     367.6
8213     493.3
8214     911.5
8215     424.1
8216     195.1
8217     105.7
8218     512.9
8219     141.5
8220     433.4
8221     310.8
8222     874.4
8223     833.1
8224     632.3
8225     229.8
8226     609.3
8227     262.3
8228     749.7
8229     668.4
8230     773.4
8231     966.8
8232     376.8
8233     584.9
8234     200.8
8235     662.5
8236     359.3
8237     184.6
8238     407.5
8239     422.6
8240     926.9
8241     222.7
8242     177.7
8243     631.8
8244     158.1
8245     613.1
8246     798.6
8247     688.0
8248     540.7
8249     569.9
8250     275.1
8251     610.8
8252     819.3
8253     122.8
8254     134.0
8255     867.6
8256     843.7
8257     299.6
8258     956.0
8259     287.4
8260     305.1
8261     740.3
8262     355.9
8263     907.5
8264     225.2
8265     429.6
8266     847.5
8267     499.0
8268     331.0
8269     107.5
8270      49.3
8271     149.3
8272     243.3
8273     736.8
8274     781.5
8275     762.9
8276     193.7
8277     791.8
8278     731.3
8279     137.7
8280     782.0
8281     853.7
8282     113.6
8283     355.7
8284      44.8
8285     866.3
8286     468.4
8287     862.8
8288      70.4
8289     662.6
8290      55.7
8291     525.5
8292     416.8
8293     441.7
8294     512.0
8295      50.2
8296     656.0
8297     196.9
8298     334.5
8299      34.7
8300     727.3
8301     318.7
8302     597.1
8303     611.2
8304     135.1
8305      27.3
8306     786.3
8307     631.0
8308     370.0
8309      35.4
8310     945.8
8311     610.1
8312     444.2
8313     465.2
8314     340.8
8315     253.9
8316     905.8
8317     774.8
8318     617.3
8319     530.8
8320     483.4
8321     742.3
8322     372.1
8323     591.0
8324     364.7
8325     545.4
8326     662.1
8327     568.9
8328     661.1
8329     598.5
8330     525.0
8331     704.1
8332     375.0
8333     748.3
8334     425.9
8335     533.4
8336     361.6
8337      33.2
8338     544.8
8339     462.6
8340     912.6
8341     463.5
8342     938.1
8343     169.5
8344     782.2
8345     716.6
8346     220.0
8347     887.6
8348     615.5
8349     454.2
8350     635.0
8351     235.3
8352     335.1
8353     503.4
8354     609.1
8355     537.4
8356     803.0
8357     150.4
8358      36.7
8359     604.7
8360     259.5
8361     765.8
8362     155.6
8363     907.2
8364     164.4
8365     534.9
8366     222.4
8367     339.5
8368      29.6
8369     215.6
8370     892.4
8371      39.3
8372     747.8
8373     770.0
8374     549.9
8375     275.8
8376     603.8
8377     241.4
8378     470.0
8379     115.2
8380     383.8
8381      33.9
8382     231.3
8384     590.5
8385     454.4
8386     595.6
8387     565.1
8388     160.4
8389     223.8
8390     285.7
8391     741.5
8392     100.7
8393     179.9
8394     972.7
8395     579.9
8396     897.7
8397     684.7
8398     530.6
8399     170.3
8400     297.0
8401     744.1
8402     386.3
8403     939.8
8404     575.5
8405     312.5
8406     553.6
8407     345.4
8408     303.1
8409     935.8
8410     629.1
8411      42.7
8412     639.9
8413      83.6
8414     958.7
8415     312.7
8416     578.4
8417     588.1
8418      72.2
8419     891.7
8420     519.3
8421     813.5
8422     536.0
8423     272.5
8424     598.5
8425     329.7
8426     454.4
8427     434.0
8428     248.4
8429     937.0
8430     260.7
8431     294.6
8432     375.3
8433     398.5
8434     349.7
8435     276.9
8436     171.8
8437     408.3
8438     421.5
8439     757.5
8440      87.4
8441      21.9
8442     944.7
8443     471.4
8444     722.8
8445     190.5
8446     188.5
8447     414.8
8448     832.7
8449     163.6
8450     380.4
8451     468.6
8452     204.0
8453     781.6
8454     299.1
8455     672.2
8456     150.2
8457     552.6
8458     175.4
8459     506.3
8460     807.7
8461     265.2
8462     113.8
8463     360.6
8464     776.7
8465     864.9
8466     896.3
8467     292.7
8468     469.9
8469     743.3
8470     417.8
8471     945.8
8472     567.1
8473     282.4
8474     938.5
8475     321.2
8476     376.4
8477     193.6
8478     181.9
8479     128.0
8480     764.0
8481     189.5
8482     122.0
8483     590.6
8484     402.6
8485     228.6
8486     973.4
8487     272.7
8488     380.4
8489     291.3
8490     921.9
8491     816.4
8492     199.5
8493     791.7
8494     249.4
8495     449.3
8496     634.4
8497     105.5
8498     979.3
8499     175.5
8500     629.4
8501     500.2
8502     388.7
8503     162.1
8504      51.5
8505     735.8
8506     438.0
8507     416.5
8508     952.1
8509     873.3
8510     713.7
8511     347.9
8512     421.7
8513     638.7
8514     254.0
8515     534.9
8516     936.3
8517     527.7
8518     600.2
8519     501.2
8520     528.2
8521     782.2
8522      59.1
8523     483.3
8524     623.4
8525     767.2
8526     129.5
8527     253.3
8528     220.9
8529     186.9
8530     540.7
8531     117.3
8532     531.4
8533     106.2
8534      49.6
8535     625.0
8536     799.6
8537     345.5
8538     741.6
8539     211.9
8540     896.0
8541     561.5
8542     771.3
8543     327.5
8544     662.7
8545     762.2
8546     569.6
8547     343.5
8548     905.0
8549     146.5
8550     878.5
8551     299.6
8552     183.5
8553     817.9
8554     248.6
8555     495.9
8556     972.3
8557     612.6
8558     296.5
8559     319.8
8560     468.4
8561     114.0
8562      30.6
8563     314.1
8564     762.8
8565     149.7
8566     616.1
8567     341.4
8568      43.0
8569     936.8
8570     636.1
8571     503.9
8572     124.9
8573     116.4
8574      56.3
8575     838.6
8576     645.0
8577     601.5
8578     672.5
8579     935.3
8580     571.2
8581     850.1
8582     298.4
8583     548.4
8584     716.1
8585     818.6
8586     825.7
8587     310.6
8588     498.7
8589     806.2
8590     689.8
8591      84.8
8592     896.4
8593     416.7
8594     863.7
8595     749.3
8596     526.0
8597     392.7
8598     837.1
8599     194.9
8600      32.2
8601     225.0
8602     382.1
8603     965.2
8604     483.3
8605     671.3
8606     874.7
8607     962.8
8608     327.8
8609     670.0
8610      61.9
8611     753.7
8612     151.3
8613     871.8
8614     532.4
8615     642.7
8616     173.5
8617     948.6
8618     424.5
8619     341.1
8620     362.6
8621     547.0
8622     268.0
8623     212.4
8624     402.3
8625     375.4
8626     853.7
8627     778.5
8628     512.6
8629     439.1
8630     514.0
8631     357.4
8632     449.2
8633     257.7
8634     571.0
8635     398.6
8636     656.2
8637     641.0
8638     495.5
8639     941.7
8640     711.4
8641     546.5
8642     357.4
8643     243.9
8644     715.1
8645     721.6
8646      42.8
8647     980.7
8648     380.7
8649     803.2
8650     941.7
8651     620.9
8652     952.6
8653     238.0
8654     335.5
8655      46.4
8656     509.2
8657     172.3
8658     686.4
8659     268.9
8660     558.3
8661     741.0
8662     100.6
8663     129.8
8664     646.1
8665     734.4
8666     385.9
8667     341.6
8668     825.0
8669     233.5
8670     268.0
8671     458.2
8672     365.2
8673     603.9
8674     822.2
8675     289.4
8676     316.7
8677     638.2
8678      64.1
8679     342.2
8680     137.9
8681     384.0
8682     880.0
8683     701.6
8684     341.4
8685     443.8
8686      61.2
8687     726.2
8688     378.1
8689     379.4
8690     483.5
8691     983.9
8692     656.5
8693     472.1
8694     902.2
8695     222.6
8696     591.3
8697     236.5
8698     423.2
8699     191.4
8700     629.7
8701     258.8
8702     462.8
8703     725.9
8704     625.4
8705     197.2
8706     391.6
8707     269.9
8708     345.4
8709     348.3
8710     483.0
8711     542.6
8712     777.6
8713     942.1
8714     679.3
8715     740.3
8716     158.9
8717     615.4
8718     199.5
8719     455.4
8720     375.7
8721     523.7
8722     368.4
8723     378.4
8724     849.7
8725     891.6
8726     881.5
8727     231.1
8728     790.3
8729     436.8
8730     271.7
8731     100.8
8732     607.4
8733     910.0
8734     769.4
8735     763.3
8736     527.8
8737     473.9
8738     809.2
8739      40.6
8740     237.8
8741     396.2
8742     667.2
8743     748.4
8744     262.6
8745     845.1
8746     564.8
8747     191.1
8748     670.0
8749     208.4
8750     852.2
8751     258.2
8752     665.5
8753     899.7
8754     942.0
8755     923.9
8756     383.6
8757     666.9
8758      21.3
8759     457.6
8760     118.5
8761     802.3
8762     382.9
8763     441.7
8764     729.4
8765     732.1
8766     270.0
8767     271.2
8768     357.3
8769     868.6
8770     285.1
8771     963.3
8772     461.1
8773     515.7
8774      87.3
8775     733.0
8776     221.8
8777     291.0
8778     286.6
8779     492.8
8780      95.5
8781     593.3
8782     895.3
8783     815.5
8784     118.8
8785      29.8
8786     311.6
8787     580.9
8788     255.3
8789     739.7
8790     751.4
8791     241.5
8792      77.6
8793     797.7
8794     920.1
8795     917.8
8796      67.0
8797      95.7
8798     235.8
8799     473.2
8800     701.8
8801     516.5
8802     247.3
8803     473.5
8804     692.9
8805     700.5
8806     116.8
8807     466.2
8808     326.0
8809     111.7
8810     290.4
8811     285.0
8812     873.8
8813     433.5
8814     723.9
8815     593.7
8816     350.4
8817     148.6
8818     412.5
8819     677.6
8820     749.7
8821     773.1
8822     562.2
8823     955.4
8824     473.4
8825     928.6
8826     913.1
8827     554.2
8828     630.7
8829     456.7
8830     145.8
8831     904.0
8832      25.8
8833     580.4
8834     733.2
8835     240.7
8836     229.8
8837     784.4
8838     449.9
8839     249.3
8840     825.7
8841     314.9
8842     115.0
8843     821.3
8844     328.6
8845     293.5
8846     405.0
8847     898.2
8848     621.4
8849     306.9
8850     179.7
8851     387.6
8852     255.3
8853     251.1
8854     347.3
8855     416.8
8856     500.1
8857     600.3
8858     701.4
8859     514.7
8860     115.7
8861     763.3
8862     208.2
8863     208.6
8864     808.7
8865     438.7
8866     397.4
8867     796.7
8868     431.3
8869     112.6
8870     204.9
8871     594.0
8872     564.0
8873     975.0
8874     101.3
8875     564.3
8876     847.4
8877     746.1
8878     907.7
8879     344.9
8880     796.8
8881      83.6
8882      83.4
8883     843.9
8884     663.2
8885     121.4
8886     226.0
8887     208.7
8888     492.5
8889     641.2
8890     534.0
8891     275.9
8892     447.9
8893     270.4
8894     366.6
8895     807.1
8896     781.3
8897     670.6
8898     609.4
8899     582.7
8900     345.4
8901     755.7
8902     214.4
8903     691.3
8904     183.7
8905     785.7
8906     377.4
8907     431.3
8908     698.0
8909     245.7
8910     603.5
8911     802.2
8912     152.4
8913     693.0
8914     224.1
8915     818.6
8916     617.1
8917     583.2
8918     814.0
8919     608.8
8920     178.3
8921     417.5
8922     846.3
8923     117.4
8924     672.4
8925     681.5
8926     284.3
8927     577.7
8928     148.9
8929     768.0
8930     989.6
8931     658.8
8932     811.4
8933     330.6
8934      22.3
8935     974.1
8936      24.4
8937     206.9
8938     947.0
8939     578.5
8940     956.3
8941     402.6
8942     516.7
8943     380.3
8944      42.2
8945      55.4
8946      94.2
8947     604.9
8948     753.2
8949     345.2
8950     911.3
8951     704.9
8952     480.2
8953     116.2
8954     881.3
8955     967.8
8956     150.7
8957     489.4
8958     858.4
8959      47.0
8960     245.5
8961     875.7
8962      46.2
8963     839.3
8964     741.9
8965     373.5
8966     417.2
8967     528.0
8968     810.9
8969     959.3
8970      90.1
8971     136.9
8972     931.5
8973     753.2
8974     791.7
8975     444.5
8976     624.8
8977     174.5
8978     820.7
8979     514.3
8980     630.1
8981     731.6
8982     242.4
8983     617.0
8984     258.4
8985     267.4
8986     572.5
8987     197.6
8988     497.3
8989     401.1
8990     185.5
8991     887.8
8992     643.6
8993     517.3
8994     614.5
8995     973.2
8996     582.8
8997     680.2
8998     658.3
8999     258.7
9000     200.1
9001     498.3
9002     423.4
9003     672.9
9004     761.7
9005     548.5
9006     983.0
9007     893.5
9008     761.3
9009     795.7
9010     331.7
9011     611.9
9012     810.3
9013     195.1
9014     477.2
9015     274.5
9016     740.9
9017     226.3
9018     240.9
9019     296.1
9020     364.2
9021     278.4
9022     917.7
9023     861.7
9024     379.5
9025      64.1
9026     976.8
9027     867.1
9028     425.2
9029     204.0
9030     645.7
9031      64.1
9032     635.0
9033     104.8
9034     968.8
9035     872.5
9036      75.9
9037      50.1
9038     208.7
9039     879.3
9040     102.8
9041      48.4
9042     420.8
9043     935.9
9044     538.1
9045     307.3
9046     897.3
9047     211.2
9048      70.9
9049     145.3
9050     772.4
9051     132.1
9052     549.0
9053     852.5
9054     537.2
9055     595.3
9056     552.0
9057     230.4
9058     348.2
9059     973.8
9060     809.1
9061      56.1
9062     793.2
9063     115.8
9064     158.8
9065     113.8
9066     938.7
9067     820.4
9068      45.9
9069     403.6
9070     695.4
9071      63.9
9072     179.4
9073     765.1
9074     918.3
9075     266.3
9076     455.4
9077     835.2
9078     951.9
9079     674.3
9080     769.6
9081     738.6
9082     588.6
9083     245.6
9084     407.1
9085     665.0
9086     573.3
9087     828.1
9088     849.4
9089     416.9
9090     664.1
9091      25.3
9092      71.9
9093     618.6
9094     234.8
9095     504.8
9096      89.7
9097     901.1
9098     173.8
9099     729.6
9100     943.7
9101      91.4
9102     272.7
9103      47.8
9104     912.8
9105     473.6
9106     714.2
9107      21.9
9108     499.0
9109     182.0
9110     852.8
9111     801.9
9112     314.3
9113     528.3
9114     365.7
9115     908.9
9116      30.2
9117     734.3
9118     376.6
9119     644.1
9120     344.5
9121     426.6
9122     234.7
9123     710.0
9124     879.4
9125     326.5
9126     415.4
9127      82.6
9128     729.5
9129     966.6
9130     341.2
9131     263.3
9132     283.8
9133     397.1
9134     552.8
9135     531.8
9136     114.1
9137     892.5
9138     280.2
9139      30.9
9140     839.2
9141     577.3
9142     745.2
9143      85.9
9144      46.3
9145     932.6
9146     247.1
9147     802.2
9148     560.6
9149      17.4
9150      19.9
9151      25.0
9152      26.9
9153      29.7
9155      17.3
9156      25.1
9157       7.2
9158      14.9
9159      18.1
9160      21.1
9161       7.0
9162       7.4
9164      21.9
9165      26.4
9167      28.0
9168      25.0
9169      26.5
9171       9.8
9172      10.4
9173      29.0
9174      15.4
9175      15.6
9176      28.0
9177       8.1
9178       5.3
9179      25.8
9181      14.6
9182      21.2
9183      11.8
9185       7.2
9187      13.8
9188      15.4
9189      27.9
9190      11.9
9191      19.0
9192      14.2
9193      24.7
9194      15.0
9195      11.7
9196      27.1
9197      15.3
9198      28.4
9199      15.4
9200      25.8
9201      18.0
9202      11.9
9204      29.2
9206      25.4
9210      28.0
9211       5.8
9212       8.8
9213      26.5
9214       8.0
9216      14.7
9217      27.9
9218      17.0
9220       5.4
9222      25.8
9223      16.8
9224      12.9
9225      23.4
9227      17.2
9228      26.2
9229      27.0
9231      19.0
9232       9.0
9233       6.7
9234      16.5
9235      24.6
9236      28.9
9238      29.4
9239      16.5
9240      24.7
9241      17.1
9243      11.6
9244      15.8

In [15]:
clean_df["Albumin"] = ((clean_df["Albumin"] - 30) / (989.9 - 30) * 5).round().clip(0, 5)

In [16]:
print(clean_df["Albumin"].describe())

count    15049.000000
mean         1.114028
std          1.601027
min         -0.000000
25%          0.000000
50%          0.000000
75%          2.000000
max          5.000000
Name: Albumin, dtype: float64

In [26]:
clean_df["Albumin"] = clean_df["Albumin"].abs()

sugar

In [17]:
clean_df.loc[clean_df["Sugar"].between(0, 5), "Sugar"]

0        2
1        4
2        5
3        4
4        5
5        3
6        3
7        5
8        2
9        3
10       3
11       5
12       3
13       2
14       3
15       4
16       3
17       4
18       2
19       4
20       1
21       3
22       3
23       5
24       1
25       2
26       1
27       5
28       1
29       1
30       4
31       5
32       5
33       4
34       4
35       2
36       1
37       1
38       1
39       1
40       5
41       2
42       4
43       4
44       2
45       5
46       5
47       5
48       4
49       4
50       3
51       5
52       5
53       1
54       1
55       5
56       4
57       4
58       4
59       1
60       1
61       4
62       5
63       5
64       2
65       3
66       4
67       5
68       1
69       3
70       2
71       1
72       1
73       5
74       4
75       2
76       2
77       1
78       1
79       4
80       4
81       5
82       5
83       2
84       4
85       5
86       1
87       3
88       3
89       3
90       1
91       4
92       5
93       2
94       1
95       4
96       5
97       3
98       4
99       1
100      3
101      5
102      4
103      5
104      5
105      1
106      1
107      3
108      2
109      4
110      2
111      5
112      2
113      2
114      4
115      2
116      4
117      4
118      1
119      4
120      2
121      1
122      2
123      4
124      1
125      2
126      5
127      3
128      4
129      4
130      1
131      3
132      3
133      3
134      5
135      2
136      1
137      3
138      4
139      4
140      5
141      5
142      1
143      1
144      4
145      5
146      2
147      4
148      1
149      2
150      4
151      1
152      4
153      2
154      5
155      3
156      5
157      5
158      4
159      4
160      4
161      3
162      4
163      3
164      2
165      3
166      5
167      3
168      3
169      5
170      4
171      5
172      2
173      4
174      5
175      4
176      5
177      5
178      5
179      5
180      4
181      3
182      4
183      5
184      5
185      4
186      3
187      4
188      2
189      1
190      2
191      1
192      4
193      5
194      1
195      2
196      2
197      5
198      3
199      1
200      3
201      4
202      3
203      2
204      3
205      3
206      2
207      4
208      5
209      2
210      5
211      2
212      4
213      1
214      4
215      4
216      3
217      5
218      2
219      1
220      2
221      3
222      5
223      5
224      1
225      1
226      3
227      3
228      5
229      2
230      4
231      4
232      4
233      1
234      2
235      4
236      3
237      1
238      4
239      1
240      0
241      0
242      1
243      1
244      1
245      1
246      1
247      1
248      0
249      0
250      1
251      1
252      1
253      1
254      0
255      0
256      0
257      0
258      1
259      1
260      1
261      0
262      1
263      1
264      1
265      0
266      0
267      1
268      1
269      1
270      1
271      1
272      1
273      0
274      0
275      0
276      1
277      1
278      1
279      0
280      1
281      0
282      1
283      0
284      1
285      1
286      0
287      0
288      0
289      1
290      0
291      1
292      0
293      0
294      1
295      0
296      0
297      0
298      0
299      0
300      1
301      0
302      0
303      1
304      0
305      1
306      1
307      0
308      0
309      1
310      0
311      1
312      1
313      0
314      1
315      1
316      1
317      0
318      1
319      1
320      0
321      1
322      0
323      0
324      1
325      0
326      0
327      1
328      0
329      1
330      0
331      1
332      0
333      0
334      1
335      1
336      1
337      1
338      0
339      0
340      0
341      0
342      1
343      1
344      1
345      0
346      1
347      1
348      0
349      1
350      0
351      0
352      0
353      0
354      1
355      1
356      0
357      1
358      1
359      1
360      1
361      0
362      1
363      0
364      0
365      0
366      0
367      1
368      0
369      1
370      1
371      1
372      0
373      1
374      0
375      1
376      1
377      0
378      1
379      0
380      1
381      0
382      0
383      1
384      0
385      1
386      0
387      0
388      1
389      1
390      1
391      1
392      1
393      0
394      1
395      0
396      0
397      1
398      1
399      0
400      1
401      0
402      0
403      0
404      1
405      1
406      0
407      1
408      1
409      0
410      1
411      0
412      1
413      1
414      0
415      1
416      1
417      1
418      1
419      0
420      1
421      0
422      1
423      0
424      0
425      0
426      1
427      0
428      0
429      1
430      1
431      1
432      1
433      1
434      1
435      0
436      0
437      0
438      1
439      0
440      0
441      1
442      0
443      0
444      1
445      1
446      0
447      0
448      0
449      0
450      1
451      0
452      0
453      1
454      1
455      0
456      0
457      1
458      0
459      0
460      1
461      1
462      0
463      0
464      0
465      1
466      0
467      1
468      0
469      0
470      1
471      1
472      0
473      0
474      0
475      1
476      1
477      1
478      0
479      0
480      0
481      1
482      1
483      0
484      0
485      0
486      1
487      0
488      0
489      1
490      0
491      0
492      1
493      0
494      0
495      0
496      1
497      0
498      1
499      1
500      0
501      0
502      0
503      0
504      1
505      1
506      0
507      1
508      1
509      0
510      1
511      0
512      1
513      0
514      1
515      1
516      1
517      1
518      0
519      0
520      0
521      0
522      0
523      0
524      1
525      1
526      0
527      1
528      1
529      0
530      1
531      1
532      1
533      1
534      0
535      0
536      0
537      0
538      0
539      1
540      0
541      0
542      1
543      1
544      1
545      0
546      1
547      1
548      0
549      1
550      0
551      0
552      0
553      1
554      0
555      0
556      0
557      0
558      0
559      0
560      0
561      0
562      1
563      0
564      1
565      1
566      1
567      0
568      1
569      0
570      1
571      0
572      1
573      0
574      0
575      0
576      0
577      1
578      1
579      0
580      1
581      0
582      1
583      0
584      1
585      0
586      0
587      1
588      0
589      1
590      0
591      1
592      1
593      1
594      0
595      0
596      1
597      0
598      0
599      0
600      1
601      1
602      1
603      0
604      1
605      1
606      0
607      0
608      1
609      1
610      0
611      1
612      0
613      0
614      1
615      1
616      1
617      0
618      0
619      0
620      1
621      0
622      1
623      1
624      0
625      1
626      1
627      0
628      1
629      0
630      0
631      1
632      1
633      0
634      1
635      0
636      1
637      1
638      0
639      0
640      0
641      1
642      0
643      0
644      0
645      1
646      0
647      1
648      0
649      1
650      0
651      0
652      0
653      1
654      0
655      1
656      0
657      1
658      1
659      1
660      1
661      0
662      1
663      1
664      1
665      0
666      1
667      1
668      0
669      0
670      1
671      0
672      0
673      1
674      1
675      1
676      0
677      1
678      1
679      0
680      0
681      1
682      0
683      1
684      1
685      1
686      0
687      0
688      0
689      0
690      1
691      1
692      0
693      1
694      0
695      1
696      1
697      0
698      0
699      1
700      0
701      0
702      1
703      0
704      1
705      1
706      1
707      1
708      1
709      0
710      1
711      0
712      1
713      0
714      1
715      1
716      0
717      1
718      1
719      0
720      1
721      0
722      1
723      1
724      1
725      1
726      0
727      1
728      1
729      0
730      1
731      0
732      0
733      0
734      1
735      1
736      0
737      0
738      0
739      0
740      0
741      0
742      0
743      1
744      0
745      1
746      1
747      0
748      0
749      0
750      1
751      0
752      1
753      0
754      0
755      0
756      1
757      0
758      1
759      1
760      1
761      0
762      1
763      1
764      1
765      0
766      0
767      0
768      0
769      0
770      1
771      1
772      0
773      1
774      1
775      0
776      1
777      0
778      1
779      0
780      0
781      0
782      0
783      1
784      0
785      0
786      1
787      0
788      0
789      0
790      0
791      0
792      1
793      1
794      0
795      0
796      1
797      0
798      1
799      0
800      0
801      0
802      0
803      0
804      0
805      1
806      1
807      1
808      0
809      1
810      1
811      0
812      1
813      0
814      0
815      0
816      1
817      1
818      1
819      0
820      1
821      0
822      0
823      0
824      0
825      0
826      0
827      1
828      1
829      0
830      0
831      1
832      0
833      1
834      1
835      0
836      1
837      0
838      1
839      1
840      0
841      1
842      1
843      1
844      0
845      0
846      1
847      0
848      1
849      1
850      1
851      1
852      1
853      1
854      0
855      1
856      0
857      1
858      1
859      0
860      0
861      1
862      1
863      1
864      1
865      0
866      1
867      0
868      1
869      1
870      1
871      1
872      1
873      0
874      0
875      1
876      1
877      0
878      0
879      0
880      0
881      0
882      0
883      0
884      0
885      0
886      1
887      0
888      1
889      0
890      0
891      1
892      0
893      0
894      0
895      0
896      0
897      0
898      0
899      1
900      0
901      0
902      0
903      0
904      1
905      1
906      0
907      0
908      0
909      0
910      0
911      1
912      0
913      0
914      1
915      1
916      0
917      1
918      0
919      0
920      0
921      1
922      0
923      0
924      0
925      1
926      1
927      1
928      0
929      1
930      0
931      1
932      0
933      0
934      1
935      1
936      1
937      0
938      0
939      1
940      1
941      0
942      1
943      1
944      1
945      0
946      1
947      0
948      1
949      0
950      1
951      0
952      0
953      0
954      0
955      0
956      0
957      1
958      0
959      1
960      0
961      0
962      0
963      0
964      1
965      1
966      1
967      1
968      1
969      1
970      0
971      1
972      1
973      0
974      0
975      1
976      0
977      0
978      0
979      0
980      1
981      1
982      1
983      0
984      1
985      0
986      1
987      1
988      0
989      0
990      1
991      0
992      1
993      1
994      1
995      0
996      1
997      0
998      1
999      0
1000     1
1001     0
1002     0
1003     1
1004     1
1005     0
1006     1
1007     0
1008     1
1009     1
1010     0
1011     0
1012     1
1013     0
1014     1
1015     1
1016     1
1017     1
1018     0
1019     0
1020     0
1021     1
1022     1
1023     0
1024     1
1025     0
1026     0
1027     0
1028     0
1029     1
1030     1
1031     1
1032     1
1033     0
1034     1
1035     1
1036     0
1037     1
1038     0
1039     1
1040     0
1041     1
1042     1
1043     1
1044     0
1045     1
1046     0
1047     1
1048     1
1049     1
1050     1
1051     0
1052     1
1053     1
1054     1
1055     1
1056     1
1057     0
1058     1
1059     0
1060     1
1061     1
1062     0
1063     1
1064     0
1065     1
1066     0
1067     0
1068     0
1069     1
1070     0
1071     0
1072     1
1073     0
1074     0
1075     1
1076     1
1077     0
1078     1
1079     0
1080     0
1081     1
1082     1
1083     0
1084     0
1085     0
1086     1
1087     0
1088     0
1089     1
1090     1
1091     1
1092     0
1093     0
1094     1
1095     0
1096     1
1097     1
1098     1
1099     1
1100     0
1101     0
1102     1
1103     0
1104     0
1105     0
1106     0
1107     1
1108     0
1109     0
1110     1
1111     1
1112     1
1113     1
1114     1
1115     1
1116     1
1117     1
1118     0
1119     1
1120     1
1121     0
1122     1
1123     0
1124     0
1125     1
1126     0
1127     1
1128     1
1129     1
1130     0
1131     0
1132     0
1133     1
1134     1
1135     1
1136     0
1137     0
1138     1
1139     0
1140     1
1141     1
1142     1
1143     1
1144     0
1145     1
1146     1
1147     0
1148     1
1149     0
1150     1
1151     1
1152     0
1153     0
1154     0
1155     0
1156     0
1157     0
1158     1
1159     0
1160     0
1161     0
1162     0
1163     1
1164     0
1165     1
1166     1
1167     1
1168     0
1169     1
1170     1
1171     1
1172     0
1173     1
1174     0
1175     0
1176     1
1177     0
1178     1
1179     1
1180     1
1181     0
1182     1
1183     0
1184     1
1185     0
1186     1
1187     0
1188     0
1189     0
1190     1
1191     1
1192     0
1193     0
1194     1
1195     1
1196     0
1197     1
1198     1
1199     0
1200     1
1201     1
1202     1
1203     1
1204     0
1205     1
1206     0
1207     1
1208     1
1209     0
1210     1
1211     0
1212     1
1213     0
1214     1
1215     0
1216     0
1217     1
1218     0
1219     0
1220     1
1221     1
1222     0
1223     1
1224     1
1225     0
1226     1
1227     1
1228     1
1229     0
1230     0
1231     0
1232     0
1233     0
1234     0
1235     0
1236     1
1237     0
1238     1
1239     1
1240     0
1241     0
1242     0
1243     0
1244     0
1245     0
1246     0
1247     0
1248     1
1249     0
1250     0
1251     1
1252     0
1253     0
1254     0
1255     1
1256     0
1257     1
1258     0
1259     0
1260     1
1261     1
1262     1
1263     1
1264     1
1265     0
1266     1
1267     1
1268     1
1269     1
1270     0
1271     1
1272     1
1273     0
1274     1
1275     1
1276     1
1277     0
1278     0
1279     0
1280     0
1281     1
1282     0
1283     0
1284     1
1285     0
1286     0
1287     0
1288     0
1289     1
1290     0
1291     1
1292     0
1293     0
1294     1
1295     0
1296     0
1297     1
1298     0
1299     1
1300     1
1301     1
1302     1
1303     1
1304     0
1305     1
1306     1
1307     0
1308     1
1309     0
1310     0
1311     0
1312     1
1313     0
1314     1
1315     0
1316     0
1317     0
1318     0
1319     1
1320     0
1321     0
1322     1
1323     0
1324     1
1325     0
1326     1
1327     0
1328     0
1329     0
1330     0
1331     1
1332     1
1333     1
1334     0
1335     1
1336     0
1337     0
1338     0
1339     1
1340     1
1341     0
1342     0
1343     1
1344     0
1345     0
1346     0
1347     1
1348     1
1349     0
1350     1
1351     1
1352     1
1353     1
1354     1
1355     1
1356     0
1357     1
1358     1
1359     0
1360     1
1361     0
1362     0
1363     0
1364     1
1365     0
1366     0
1367     0
1368     0
1369     0
1370     0
1371     0
1372     1
1373     1
1374     1
1375     1
1376     1
1377     1
1378     0
1379     1
1380     1
1381     1
1382     0
1383     1
1384     1
1385     1
1386     0
1387     1
1388     1
1389     1
1390     0
1391     1
1392     1
1393     1
1394     1
1395     0
1396     1
1397     1
1398     0
1399     1
1400     1
1401     1
1402     0
1403     1
1404     1
1405     1
1406     0
1407     1
1408     1
1409     0
1410     0
1411     1
1412     1
1413     1
1414     1
1415     0
1416     0
1417     0
1418     0
1419     1
1420     1
1421     1
1422     1
1423     0
1424     0
1425     0
1426     0
1427     1
1428     0
1429     0
1430     1
1431     1
1432     1
1433     1
1434     0
1435     0
1436     0
1437     1
1438     0
1439     1
1440     0
1441     0
1442     1
1443     0
1444     0
1445     0
1446     0
1447     0
1448     0
1449     1
1450     0
1451     0
1452     0
1453     1
1454     1
1455     1
1456     0
1457     1
1458     0
1459     0
1460     0
1461     0
1462     0
1463     1
1464     1
1465     1
1466     0
1467     0
1468     1
1469     0
1470     1
1471     1
1472     0
1473     0
1474     1
1475     1
1476     1
1477     0
1478     0
1479     0
1480     1
1481     0
1482     1
1483     0
1484     1
1485     1
1486     0
1487     0
1488     0
1489     1
1490     0
1491     0
1492     0
1493     0
1494     1
1495     1
1496     1
1497     1
1498     1
1499     0
1500     1
1501     1
1502     0
1503     1
1504     0
1505     1
1506     1
1507     0
1508     1
1509     0
1510     0
1511     0
1512     1
1513     1
1514     0
1515     0
1516     1
1517     0
1518     0
1519     0
1520     1
1521     1
1522     1
1523     0
1524     1
1525     1
1526     1
1527     0
1528     1
1529     1
1530     0
1531     0
1532     1
1533     0
1534     0
1535     0
1536     1
1537     0
1538     0
1539     0
1540     0
1541     0
1542     1
1543     0
1544     0
1545     0
1546     1
1547     1
1548     1
1549     1
1550     1
1551     1
1552     1
1553     0
1554     0
1555     0
1556     0
1557     1
1558     1
1559     0
1560     1
1561     1
1562     1
1563     0
1564     1
1565     0
1566     0
1567     1
1568     1
1569     1
1570     1
1571     0
1572     0
1573     0
1574     0
1575     0
1576     1
1577     0
1578     0
1579     1
1580     0
1581     1
1582     0
1583     1
1584     0
1585     0
1586     0
1587     1
1588     1
1589     1
1590     0
1591     1
1592     0
1593     1
1594     0
1595     0
1596     1
1597     0
1598     0
1599     0
1600     1
1601     0
1602     0
1603     1
1604     1
1605     0
1606     0
1607     0
1608     0
1609     1
1610     1
1611     1
1612     1
1613     0
1614     0
1615     1
1616     1
1617     1
1618     0
1619     1
1620     0
1621     1
1622     1
1623     1
1624     1
1625     1
1626     0
1627     1
1628     0
1629     1
1630     0
1631     0
1632     1
1633     0
1634     1
1635     0
1636     0
1637     1
1638     0
1639     0
1640     1
1641     0
1642     0
1643     1
1644     1
1645     0
1646     0
1647     0
1648     0
1649     0
1650     0
1651     1
1652     1
1653     0
1654     1
1655     0
1656     0
1657     0
1658     0
1659     1
1660     1
1661     1
1662     0
1663     0
1664     0
1665     0
1666     1
1667     1
1668     0
1669     1
1670     0
1671     0
1672     1
1673     1
1674     1
1675     0
1676     1
1677     0
1678     1
1679     0
1680     0
1681     1
1682     1
1683     0
1684     1
1685     1
1686     0
1687     0
1688     0
1689     0
1690     0
1691     1
1692     0
1693     1
1694     1
1695     0
1696     0
1697     0
1698     1
1699     1
1700     1
1701     0
1702     1
1703     0
1704     0
1705     0
1706     1
1707     1
1708     1
1709     0
1710     0
1711     1
1712     0
1713     0
1714     0
1715     1
1716     1
1717     1
1718     1
1719     0
1720     1
1721     1
1722     0
1723     1
1724     0
1725     0
1726     1
1727     0
1728     0
1729     1
1730     0
1731     0
1732     1
1733     1
1734     0
1735     0
1736     0
1737     1
1738     0
1739     0
1740     1
1741     0
1742     0
1743     0
1744     0
1745     0
1746     0
1747     0
1748     1
1749     1
1750     0
1751     1
1752     1
1753     0
1754     0
1755     0
1756     0
1757     1
1758     1
1759     1
1760     1
1761     1
1762     0
1763     1
1764     0
1765     0
1766     1
1767     0
1768     0
1769     0
1770     0
1771     1
1772     1
1773     1
1774     0
1775     1
1776     1
1777     0
1778     0
1779     0
1780     1
1781     1
1782     0
1783     1
1784     0
1785     0
1786     0
1787     1
1788     1
1789     1
1790     0
1791     0
1792     1
1793     0
1794     0
1795     1
1796     1
1797     0
1798     0
1799     0
1800     0
1801     1
1802     1
1803     0
1804     0
1805     0
1806     1
1807     0
1808     1
1809     0
1810     1
1811     1
1812     1
1813     0
1814     0
1815     0
1816     0
1817     1

In [18]:
clean_df.loc[~clean_df["Sugar"].between(0, 5), "Sugar"]

7892      237
7893      193
7894      134
7895       72
7896       63
7897       38
7898       34
7899       50
7900       61
7901      106
7902      114
7903      159
7904      227
7905       39
7906      160
7907      238
7908      130
7909       87
7910       80
7911      151
7912      227
7913       46
7914       34
7915      150
7916      222
7917      117
7918      211
7919      240
7920      137
7921      212
7922       57
7923      243
7924      166
7925      223
7926      223
7927      167
7928      138
7929      203
7930      123
7931      161
7932      231
7933       97
7934      105
7935      169
7936      250
7937       44
7938      215
7939      184
7940      225
7941      232
7942       66
7943      177
7944      141
7945      121
7946      170
7947      192
7948      177
7949       86
7950      180
7951      147
7952      147
7953      146
7954       81
7955      122
7956      171
7957      223
7958      140
7959       56
7960      158
7961      126
7962       97
7963      111
7964      237
7965      174
7966      167
7967       65
7968      187
7969      209
7970       32
7971      202
7972       49
7973      163
7974      131
7975      145
7976      106
7977      246
7978       45
7979      175
7980      243
7981       40
7982      242
7983       30
7984      232
7985       98
7986      101
7987      248
7988      188
7989       59
7990      160
7991      190
7992      129
7993      171
7994      133
7995      232
7996      130
7997      183
7998       92
7999      203
8000       41
8001      175
8002       36
8003      128
8004      114
8005       34
8006      109
8007      116
8008      173
8009       78
8010       67
8011      221
8012       72
8013      204
8014      237
8015       57
8016      224
8017       85
8018      169
8019      245
8020      195
8021      124
8022      137
8023       37
8024      164
8025       56
8026      138
8027       37
8028       39
8029      172
8030       99
8031      155
8032      137
8033       73
8034      114
8035       91
8036       48
8037      194
8038      206
8039       44
8040       64
8041      121
8042      522
8043      664
8044      194
8045      654
8046      513
8047      142
8048       83
8049      455
8050      164
8051       97
8052      552
8053      467
8054      424
8055      625
8056       55
8057      408
8058      814
8059      806
8060      602
8061      897
8062      686
8063      857
8064      345
8065      781
8066      791
8067      274
8068      483
8069      170
8070      599
8071      587
8072      208
8073      929
8074      824
8075      912
8076      206
8077       50
8078      122
8079      852
8080      156
8081      152
8082      224
8083      543
8084      610
8085       65
8086      665
8087      484
8088      911
8089      623
8090      893
8091      840
8092      144
8093      730
8094      877
8095      629
8096      670
8097      137
8098      426
8099       95
8100      799
8101      965
8102      934
8103      739
8104      469
8105      142
8106      567
8107      517
8108      361
8109      833
8110      824
8111       65
8112      473
8113      381
8114      701
8115      738
8116      117
8117      289
8118      264
8119      922
8120      122
8121      695
8122      228
8123      615
8124      723
8125      383
8126      533
8127      694
8128      502
8129      916
8130       79
8131      495
8132      814
8133      274
8134      201
8135      545
8136      651
8137      154
8138      474
8139      132
8140      706
8141      890
8142      158
8143      490
8144      899
8145      655
8146      196
8147      490
8148      424
8149       68
8150      674
8151      804
8152      629
8153      168
8154      266
8155      951
8156      807
8157      555
8158      301
8159      174
8160      970
8161      353
8162      510
8163      915
8164      554
8165      348
8166      353
8167      838
8168      778
8169       83
8170      952
8171      973
8172      214
8173      785
8174      752
8175      280
8176      400
8177       54
8178      367
8179      451
8180      638
8181      262
8182      737
8183      363
8184      414
8185      923
8186      286
8187      781
8188      852
8189      385
8190      985
8191      388
8192      241
8193      157
8194      105
8195      221
8196       85
8197       56
8198      234
8199      246
8200      200
8201      967
8202      331
8203      232
8204      762
8205      838
8206      795
8207      707
8208      910
8209       83
8210      308
8211      746
8212      861
8213      295
8214      972
8215       61
8216      487
8217      771
8218       98
8219      219
8220      557
8221      412
8222      399
8223       94
8224      515
8225      816
8226      527
8227      749
8228      183
8229      597
8230       64
8231      845
8232      673
8233      124
8234      565
8235      377
8236      531
8237      350
8238      196
8239      566
8240      847
8241      481
8242      438
8243      147
8244       64
8245      116
8246       88
8247       56
8248       98
8249      170
8250       42
8251      400
8252      930
8253      866
8254      851
8255      356
8256      589
8257      222
8258      458
8259      895
8260       88
8261      929
8262      131
8263      423
8264      869
8265      743
8266      553
8267      103
8268       47
8269      115
8270      229
8271      113
8272       32
8273      181
8274       33
8275      938
8276      210
8277      425
8278      113
8279      852
8280      478
8281      676
8282      749
8283      462
8284      302
8285      153
8286      218
8287      102
8288      193
8289       80
8290      220
8291       86
8292      106
8293       86
8294      189
8295      246
8296      125
8297      101
8298      225
8299      235
8300       74
8301      214
8302      995
8303      601
8304      920
8305      644
8306      769
8307      740
8308      814
8309      995
8310      466
8311       70
8312      717
8313      927
8314      102
8315       72
8316      958
8317      687
8318       77
8319      205
8320      215
8321      125
8322       77
8323      128
8324       53
8325       94
8326       34
8327       41
8328      165
8329       59
8330      232
8331       65
8332      117
8333      133
8334       78
8335      242
8336       51
8337       56
8338       40
8339      168
8340      246
8341      151
8342      100
8343       70
8344      153
8345      196
8346       59
8347       41
8348       39
8349       83
8350      159
8351      134
8352      241
8353       40
8354      108
8355       69
8356      191
8357      222
8358      183
8359      208
8360      186
8361       96
8362       61
8363       60
8364       78
8365      221
8366      207
8367      199
8368      181
8369       46
8370      210
8371      185
8372       40
8373      150
8374      209
8375      223
8376      245
8377      240
8378      143
8379      247
8380       34
8381      153
8382       96
8384      162
8385      228
8386      154
8387      131
8388      238
8389      206
8390      193
8391       84
8392      247
8393      239
8394      236
8395      146
8396       67
8397       91
8398       95
8399       60
8400      135
8401       57
8402      175
8403      184
8404      245
8405      173
8406      240
8407      241
8408       57
8409      153
8410      247
8411      236
8412      162
8413      154
8414       54
8415      122
8416      148
8417       53
8418      152
8419      152
8420      222
8421       72
8422      142
8423      184
8424      238
8425      202
8426      104
8427      124
8428       63
8429      225
8430      186
8431      102
8432      139
8433       52
8434      100
8435      222
8436      243
8437       64
8438      201
8439      209
8440      105
8441       88
8442       39
8443      207
8444      183
8445      188
8446      231
8447       67
8448      240
8449      179
8450      207
8451      235
8452      144
8453      224
8454       83
8455       85
8456      137
8457       31
8458       82
8459      117
8460      176
8461      198
8462       32
8463      123
8464       67
8465      232
8466       32
8467      195
8468      226
8469       61
8470      239
8471      198
8472      128
8473      149
8474      104
8475       96
8476      239
8477      104
8478      223
8479      110
8480      193
8481      221
8482       61
8483       88
8484      221
8485       75
8486      121
8487      199
8488      117
8489      208
8490       36
8491      236
8492      185
8493       53
8494      107
8495       50
8496      134
8497      192
8498       71
8499      133
8500      153
8501       90
8502       87
8503      186
8504       97
8505       99
8506      240
8507      126
8508      194
8509       36
8510      118
8511       73
8512       45
8513       35
8514      100
8515      160
8516      166
8517       39
8518       51
8519      200
8520      120
8521      100
8522      180
8523      117
8524      146
8525       47
8526      103
8527      169
8528      177
8529      234
8530      112
8531      150
8532      236
8533      155
8534       43
8535      182
8536      109
8537      195
8538       99
8539      161
8540       49
8541      132
8542      220
8543      234
8544      230
8545       71
8546      186
8547      228
8548       91
8549      199
8550       83
8551      132
8552      221
8553       96
8554      101
8555       39
8556       36
8557      207
8558      215
8559      199
8560      221
8561      214
8562       82
8563      240
8564      160
8565      200
8566      241
8567      141
8568      247
8569      158
8570       64
8571      247
8572       67
8573      241
8574      155
8575       96
8576       97
8577       41
8578       79
8579      233
8580      204
8581      161
8582       86
8583       98
8584      106
8585       30
8586      185
8587      177
8588       34
8589      179
8590      166
8591       70
8592      123
8593       70
8594      160
8595      145
8596       85
8597      115
8598       70
8599      229
8600      173
8601      213
8602      132
8603      116
8604       96
8605       37
8606       50
8607      217
8608      176
8609      245
8610       69
8611      110
8612      225
8613       66
8614      243
8615       63
8616       64
8617       32
8618      126
8619      234
8620      200
8621       60
8622       61
8623       37
8624      144
8625       72
8626      157
8627      212
8628      161
8629      227
8630      122
8631       67
8632      245
8633      178
8634      225
8635      209
8636      241
8637      216
8638      206
8639       56
8640      188
8641      245
8642      203
8643      116
8644       80
8645       70
8646       58
8647      233
8648      181
8649      115
8650      193
8651       52
8652      225
8653      234
8654      156
8655      105
8656      191
8657      249
8658       49
8659      223
8660      109
8661      106
8662      141
8663      225
8664      220
8665       77
8666       94
8667       49
8668      226
8669      234
8670      120
8671       74
8672      134
8673       56
8674      112
8675      185
8676       88
8677      145
8678       52
8679      248
8680       48
8681      155
8682      167
8683      151
8684      212
8685      186
8686      102
8687      202
8688      235
8689      199
8690       35
8691       92
8692      203
8693      141
8694       98
8695       54
8696       43
8697      228
8698       66
8699       40
8700       82
8701       69
8702      164
8703      139
8704      175
8705      166
8706      208
8707      140
8708      153
8709      135
8710       81
8711       30
8712       73
8713      105
8714       46
8715      187
8716       51
8717      174
8718       75
8719      197
8720      121
8721       99
8722       38
8723       84
8724      101
8725      166
8726      248
8727      190
8728      194
8729      223
8730      110
8731      213
8732      117
8733      177
8734      134
8735       72
8736       72
8737      219
8738       86
8739       40
8740      166
8741      198
8742      193
8743      221
8744      237
8745      191
8746      114
8747      165
8748      100
8749      168
8750       60
8751       50
8752      188
8753      170
8754      221
8755       39
8756       65
8757      126
8758      180
8759      200
8760       79
8761       93
8762       58
8763      222
8764       78
8765      151
8766      172
8767      223
8768       40
8769      162
8770       95
8771       62
8772      216
8773      163
8774      161
8775      160
8776      118
8777       34
8778      188
8779       91
8780      136
8781       79
8782       32
8783      168
8784      248
8785       75
8786       58
8787      236
8788      211
8789       67
8790      122
8791       86
8792      142
8793      182
8794      147
8795      173
8796      140
8797       37
8798      110
8799      142
8800      114
8801       36
8802      121
8803      144
8804       41
8805      110
8806      184
8807       42
8808       84
8809      159
8810       77
8811      140
8812      248
8813      150
8814      181
8815      113
8816      211
8817      205
8818       31
8819       69
8820       46
8821      110
8822       40
8823      233
8824      159
8825       77
8826      237
8827      163
8828       78
8829      101
8830      174
8831      244
8832       45
8833      230
8834       72
8835      185
8836       60
8837      242
8838      247
8839      141
8840      212
8841      237
8842       48
8843       90
8844      149
8845      140
8846      175
8847       97
8848      141
8849       92
8850      156
8851       80
8852       62
8853      160
8854      182
8855      178
8856       67
8857       59
8858      143
8859      199
8860      172
8861      128
8862      201
8863      114
8864       52
8865      245
8866      103
8867       87
8868      103
8869      244
8870       31
8871      126
8872      119
8873      198
8874       98
8875      134
8876      214
8877      146
8878      218
8879       42
8880      158
8881      139
8882       67
8883      204
8884      116
8885       77
8886       98
8887      119
8888       63
8889      158
8890      164
8891       59
8892       59
8893      192
8894      110
8895      141
8896       89
8897      164
8898      105
8899       87
8900      197
8901       97
8902      228
8903      141
8904      215
8905      181
8906       79
8907      137
8908      228
8909      247
8910       34
8911      169
8912      122
8913      178
8914      151
8915      214
8916      137
8917      150
8918      186
8919      249
8920      188
8921      121
8922      145
8923      168
8924      160
8925      140
8926      216
8927      121
8928      104
8929      169
8930      220
8931      200
8932      158
8933      220
8934       84
8935       36
8936       31
8937      149
8938      158
8939      240
8940      171
8941      143
8942      205
8943       55
8944      111
8945      210
8946      235
8947      177
8948      226
8949      105
8950      168
8951      108
8952      250
8953      124
8954       70
8955      133
8956       40
8957       80
8958      227
8959      203
8960      168
8961      110
8962       83
8963      231
8964      120
8965      154
8966       33
8967       74
8968      235
8969      137
8970      197
8971       81
8972      147
8973      238
8974      110
8975       84
8976       95
8977      235
8978       57
8979      140
8980      179
8981       46
8982      133
8983      203
8984      119
8985       98
8986      243
8987       68
8988      246
8989      224
8990       74
8991       78
8992      216
8993      102
8994      191
8995      225
8996       81
8997      166
8998      207
8999      128
9000      133
9001      169
9002      127
9003      161
9004      202
9005      142
9006       90
9007       89
9008      103
9009       53
9010       88
9011      134
9012       90
9013      239
9014      131
9015       44
9016      125
9017       93
9018       96
9019       69
9020      105
9021      185
9022      230
9023      172
9024      108
9025       58
9026      243
9027       43
9028      225
9029       68
9030      179
9031      247
9032       52
9033      145
9034      233
9035       35
9036       49
9037      114
9038      186
9039      719
9040       97
9041      243
9042       66
9043      204
9044      165
9045      174
9046      110
9047       92
9048       41
9049      119
9050      244
9051       77
9052      126
9053      142
9054       91
9055      145
9056      207
9057      217
9058      209
9059      142
9060      193
9061      186
9062      187
9063       60
9064      214
9065      139
9066       52
9067      219
9068       47
9069      171
9070      130
9071      140
9072       48
9073       95
9074      185
9075      240
9076       77
9077      131
9078      244
9079      134
9080      128
9081       77
9082      113
9083      184
9084      127
9085      233
9086      138
9087      113
9088      212
9089      179
9090      114
9091       76
9092      152
9093      200
9094       52
9095      244
9096      111
9097      192
9098      111
9099      197
9100       41
9101      225
9102      170
9103      223
9104      235
9105       59
9106      239
9107      230
9108      125
9109      208
9110      166
9111      175
9112      149
9113      152
9114      113
9115      214
9116      209
9117      126
9118      235
9119       45
9120      148
9121      227
9122       34
9123       84
9124      123
9125      246
9126       64
9127      483
9128      181
9129      231
9130       37
9131      212
9132      129
9133      115
9134      200
9135      137
9136      166
9137      200
9138       84
9139      173
9140       57
9141      121
9142       86
9143      107
9144      136
9145      102
9146       85
9147      227
9148       99
9149      223
9150       57
9151      110
9152      145
9153      210
9154      221
9155      127
9156      132
9157       83
9158      239
9159       71
9160       56
9161      193
9162       46
9163       61
9164      115
9165       56
9166      166
9167       57
9168      228
9169       64
9170       41
9171       59
9172      144
9173      116
9174      169
9175      159
9176      233
9177      142
9178      185
9179      207
9180       75
9181      104
9182      193
9183      225
9184       34
9185      199
9186      223
9187      181
9188       99
9189      242
9190       65
9191      197
9192       79
9193      133
9194       62
9195       78
9196       63
9197      193
9198       50
9199       66
9200      124
9201      250
9202      203
9203      155
9204      226
9205      215
9206       51
9207       64
9208      211
9209      159
9210       40
9211      223
9212      100
9213      148
9214      192
9215      631
9216       76
9217       55
9218      201
9219      167
9220      209
9221      153
9222      247
9223       64
9224       76
9225      127
9226       76
9227      124
9228      192
9229      145
9230      180
9231      158
9232       68
9233      197
9234      231
9235       44
9236      104
9237      158
9238      209
9239       72
9240      167
9241      191
9242      137
9243      186
9244      104
9245       51
9246      163
9247       82
9248       55
9249      213
9250      170
9251       77
9252      133
9253       53
9254       52
9255      119
9256      222
9257       45
9258      195
9259      240
9260       45
9261      160
9262      220
9263      160
9264       93
9265      150
9266      193
9267      154
9268      168
9269      183
9270       48
9271       59
9272       31
9273       66
9274       78
9275      232
9276      130
9277      171
9278      109
9279      176
9280       82
9281      120
9282       98
9283       63
9284       64
9285      170
9286      228
9287       62
9288      224
9289      112
9290       39
9291       78
9292      170
9293       91
9294       57
9295      182
9296      156
9297       49
9298       70
9299      129
9300       92
9301      157
9302       30
9303      140
9304      203
9305      117
9306      239
9307      159
9308      221
9309      162
9310      228
9311      162
9312      242
9313      135
9314      230
9315       41
9316      243
9317      137
9318       69
9319      110
9320      178

In [19]:
 clean_df["Sugar"] = ((clean_df["Sugar"] - 30) / (1000 - 30) * 5).round().clip(0, 5)

In [20]:
print(clean_df["Sugar"].describe())

count    15049.000000
mean         0.717124
std          1.266119
min         -0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max          5.000000
Name: Sugar, dtype: float64

In [21]:
clean_df["Sugar"] = clean_df["Sugar"].abs()

In [24]:
print(clean_df.isna().sum())

Patient_ID                 0
Age                        0
Blood_Pressure             0
Specific_Gravity           0
Albumin                    0
Sugar                      0
Red_Blood_Cells            0
Pus_Cells                  0
Pus_Cell_Clumps            9
Bacteria                   6
Blood_Glucose_Random       0
Blood_Urea                 0
Serum_Creatinine           9
Sodium                     0
Potassium                  0
Hemoglobin                 0
Packed_Cell_Volume         0
White_Blood_Cell_Count     0
Red_Blood_Cell_Count       0
Appetite                   1
Chronic_Kidney_Disease     0
Age_Group                  0
Blood_Pressure_Category    0
Blood_Glucose_Category     0
dtype: int64

In [28]:
print(clean_df.describe().T)

                          count         mean          std       min      25%  \
Patient_ID              15049.0  7524.787760  4345.235157     0.000  3762.00
Age                     15049.0    52.101070    17.555307     2.000    45.00
Blood_Pressure          15049.0    93.233238    19.907460    50.000    80.00
Specific_Gravity        15049.0     1.024573     0.005780     1.005     1.02
Albumin                 15049.0     1.114028     1.601027     0.000     0.00
Sugar                   15049.0     0.717124     1.266119     0.000     0.00
Blood_Glucose_Random    15049.0   157.609276    62.356325    70.000   105.00
Blood_Urea              15049.0    59.641232    42.506447    10.000    25.00
Serum_Creatinine        15040.0     3.223719     5.479708     0.400     0.93
Sodium                  15049.0   138.583913     5.822992   120.000   135.00
Potassium               15049.0     5.384605     0.859755     3.500     4.79
Hemoglobin              15049.0    11.999814     2.410099     6.000    10.00
Packed_Cell_Volume      15049.0    36.843657     7.394388    20.000    30.50
White_Blood_Cell_Count  15049.0  7624.261346  2250.260836  3044.000  5691.00
Red_Blood_Cell_Count    15049.0     4.382530     1.022925     2.500     3.50

                             50%       75%       max
Patient_ID              7524.000  11288.00  15050.00
Age                       55.000     65.00     90.00
Blood_Pressure            94.000    107.00    180.00
Specific_Gravity           1.025      1.03      1.03
Albumin                    0.000      2.00      5.00
Sugar                      0.000      1.00      5.00
Blood_Glucose_Random     139.000    208.00    300.00
Blood_Urea                40.000     93.50    200.00
Serum_Creatinine           1.400      3.25     76.00
Sodium                   139.000    143.00    150.00
Potassium                  5.400      6.09      7.50
Hemoglobin                12.000     14.00     16.00
Packed_Cell_Volume        36.000     43.00     50.00
White_Blood_Cell_Count  7628.000   9505.00  11999.00
Red_Blood_Cell_Count       4.500      5.30      6.00

feature engineering

In [22]:
clean_df["Age_Group"] = pd.cut(
    clean_df["Age"],
    bins=[-np.inf, 18, 40, 60, np.inf],
    labels=["child", "young_adult", "middle_aged", "senior"],
    right=False
)

clean_df["Blood_Pressure_Category"] = pd.cut(
    clean_df["Blood_Pressure"],
    bins=[-np.inf, 90, 120, 140, np.inf],
    labels=["low", "normal", "elevated", "high"],
    right=False
)

clean_df["Blood_Glucose_Category"] = pd.cut(
    clean_df["Blood_Glucose_Random"],
    bins=[-np.inf, 70, 140, 200, np.inf],
    labels=["low", "normal", "elevated", "high"],
    right=False
)

print(clean_df[[
    "Age",
    "Age_Group",
    "Blood_Pressure",
    "Blood_Pressure_Category",
    "Blood_Glucose_Random",
    "Blood_Glucose_Category"
]].head())

print("shape after feature engineering:", clean_df.shape)

print(clean_df[[
    "Age_Group",
    "Blood_Pressure_Category",
    "Blood_Glucose_Category"
]].isna().sum())

   Age    Age_Group  Blood_Pressure Blood_Pressure_Category  \
0   48  middle_aged             178                    high
1    7        child             138                elevated
2   62       senior             165                    high
3   48  middle_aged             141                    high
4   51  middle_aged             175                    high

   Blood_Glucose_Random Blood_Glucose_Category
0                   298                   high
1                   187               elevated
2                   286                   high
3                   165               elevated
4                   179               elevated
shape after feature engineering: (15049, 24)
Age_Group                  0
Blood_Pressure_Category    0
Blood_Glucose_Category     0
dtype: int64

In [23]:
clean_df.to_csv("data clean/data clean.csv", index=False)