In [1]:
import pandas as pd
import numpy as np
from IPython.display import display
from pathlib import Path

In [2]:
df = pd.read_csv("data/Dataset_insuficiencia_renal_crnica.csv")

In [3]:
pd.set_option('display.max_columns', 30)
pd.set_option('display.width', 120)
pd.set_option('display.max_colwidth', 70)
pd.set_option('display.max_rows', None)
print('Pandas version:', pd.__version__)
print('Ready: pandas and numpy')

Pandas version: 3.0.6
Ready: pandas and numpy

In [4]:
print("first 3 rows \n", df.head(3))
print("last 3 rows \n ", df.tail(3))

first 3 rows
    Identificación del paciente  Edad  Presión arterial  Gravedad específica de la orina  Albúmina en orina  \
0                            0    48               178                           1010.0                2.0
1                            1     7               138                           1014.0                1.0
2                            2    62               165                           1014.0                2.0

   Azúcar en orina Glóbulos rojos Células de pus Grupos de células de pus Bacterias  Glucosa en sangre aleatoria  \
0                2        anormal        anormal                 presente  presente                          298
1                4        anormal        anormal                 presente  presente                          187
2                5        anormal        anormal                 presente  presente                          286

   Urea en sangre  Creatinina sérica  Sodio en sangre  Potasio en sangre  Hemoglobina  \
0           195.0               9.08            124.0                6.0          8.0
1           111.0               7.88            133.0                6.8         11.0
2           149.0              12.89            130.0                6.0          8.0

   Volumen corpuscular empaquetado  Recuento de glóbulos blancos  Recuento de glóbulos rojos Apetito  \
0                             25.0                         11319                         3.8    bajo
1                             27.0                         11018                         2.9    bajo
2                             27.0                          5479                         4.4    bajo

  Insuficiencia renal crónica
0                          si
1                          si
2                          si
last 3 rows
         Identificación del paciente  Edad  Presión arterial  Gravedad específica de la orina  Albúmina en orina  \
15048                        15048    47               177                           1010.0                2.0
15049                        15049    60               177                           1013.0                2.0
15050                        15050    62               174                           1010.0                3.0

       Azúcar en orina Glóbulos rojos Células de pus Grupos de células de pus Bacterias  Glucosa en sangre aleatoria  \
15048                4        anormal        anormal                 presente  presente                          255
15049                2        anormal        anormal                 presente  presente                          162
15050                4        anormal        anormal                 presente  presente                          300

       Urea en sangre  Creatinina sérica  Sodio en sangre  Potasio en sangre  Hemoglobina  \
15048            45.0              10.77            126.0                6.2          8.0
15049            81.0              11.25            124.0                6.9          8.0
15050            92.0               7.83            121.0                5.6         11.0

       Volumen corpuscular empaquetado  Recuento de glóbulos blancos  Recuento de glóbulos rojos Apetito  \
15048                             24.0                          9939                         3.7    bajo
15049                             20.0                          7033                         3.8    bajo
15050                             30.0                         11617                         4.2    bajo

      Insuficiencia renal crónica
15048                          no
15049                          no
15050                          no

In [5]:
print("shape\n ", df.shape)
print("number of rows\n", df.shape[0])
print("number of columnsn", df.shape[1])

shape
  (15051, 21)
number of rows
 15051
number of columnsn 21

In [6]:
print("columns\n", df.columns.tolist())
print("index\n", df.index[:5].tolist())

columns
 ['Identificación del paciente', 'Edad', 'Presión arterial', 'Gravedad específica de la orina', 'Albúmina en orina', 'Azúcar en orina', 'Glóbulos rojos', 'Células de pus', 'Grupos de células de pus', 'Bacterias', 'Glucosa en sangre aleatoria', 'Urea en sangre', 'Creatinina sérica', 'Sodio en sangre', 'Potasio en sangre', 'Hemoglobina', 'Volumen corpuscular empaquetado', 'Recuento de glóbulos blancos', 'Recuento de glóbulos rojos', 'Apetito', 'Insuficiencia renal crónica']
index
 [0, 1, 2, 3, 4]

In [7]:
print("info \n",df.info())
print("dtypes\n",df.dtypes)
df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 15051 entries, 0 to 15050
Data columns (total 21 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Identificación del paciente      15051 non-null  int64
 1   Edad                             15051 non-null  int64
 2   Presión arterial                 15051 non-null  int64
 3   Gravedad específica de la orina  15051 non-null  float64
 4   Albúmina en orina                15051 non-null  float64
 5   Azúcar en orina                  15051 non-null  int64
 6   Glóbulos rojos                   15051 non-null  str
 7   Células de pus                   15051 non-null  str
 8   Grupos de células de pus         15042 non-null  str
 9   Bacterias                        15045 non-null  str
 10  Glucosa en sangre aleatoria      15051 non-null  int64
 11  Urea en sangre                   15051 non-null  float64
 12  Creatinina sérica                15042 non-null  float64
 13  Sodio en sangre                  15051 non-null  float64
 14  Potasio en sangre                15051 non-null  float64
 15  Hemoglobina                      15051 non-null  float64
 16  Volumen corpuscular empaquetado  15051 non-null  float64
 17  Recuento de glóbulos blancos     15051 non-null  int64
 18  Recuento de glóbulos rojos       15051 non-null  float64
 19  Apetito                          15050 non-null  str
 20  Insuficiencia renal crónica      15049 non-null  str
dtypes: float64(9), int64(6), str(6)
memory usage: 2.4 MB
info
 None
dtypes
 Identificación del paciente          int64
Edad                                 int64
Presión arterial                     int64
Gravedad específica de la orina    float64
Albúmina en orina                  float64
Azúcar en orina                      int64
Glóbulos rojos                         str
Células de pus                         str
Grupos de células de pus               str
Bacterias                              str
Glucosa en sangre aleatoria          int64
Urea en sangre                     float64
Creatinina sérica                  float64
Sodio en sangre                    float64
Potasio en sangre                  float64
Hemoglobina                        float64
Volumen corpuscular empaquetado    float64
Recuento de glóbulos blancos         int64
Recuento de glóbulos rojos         float64
Apetito                                str
Insuficiencia renal crónica            str
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 15051 entries, 0 to 15050
Data columns (total 21 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Identificación del paciente      15051 non-null  int64
 1   Edad                             15051 non-null  int64
 2   Presión arterial                 15051 non-null  int64
 3   Gravedad específica de la orina  15051 non-null  float64
 4   Albúmina en orina                15051 non-null  float64
 5   Azúcar en orina                  15051 non-null  int64
 6   Glóbulos rojos                   15051 non-null  str
 7   Células de pus                   15051 non-null  str
 8   Grupos de células de pus         15042 non-null  str
 9   Bacterias                        15045 non-null  str
 10  Glucosa en sangre aleatoria      15051 non-null  int64
 11  Urea en sangre                   15051 non-null  float64
 12  Creatinina sérica                15042 non-null  float64
 13  Sodio en sangre                  15051 non-null  float64
 14  Potasio en sangre                15051 non-null  float64
 15  Hemoglobina                      15051 non-null  float64
 16  Volumen corpuscular empaquetado  15051 non-null  float64
 17  Recuento de glóbulos blancos     15051 non-null  int64
 18  Recuento de glóbulos rojos       15051 non-null  float64
 19  Apetito                          15050 non-null  str
 20  Insuficiencia renal crónica      15049 non-null  str
dtypes: float64(9), int64(6), str(6)
memory usage: 6.4 MB

In [8]:
df = df.rename(columns={
    "Identificación del paciente": "Patient_ID",
    "Edad": "Age",
    "Presión arterial": "Blood_Pressure",
    "Gravedad específica de la orina": "Specific_Gravity",
    "Albúmina en orina": "Albumin",
    "Azúcar en orina": "Sugar",
    "Glóbulos rojos": "Red_Blood_Cells",
    "Células de pus": "Pus_Cells",
    "Grupos de células de pus": "Pus_Cell_Clumps",
    "Bacterias": "Bacteria",
    "Glucosa en sangre aleatoria": "Blood_Glucose_Random",
    "Urea en sangre": "Blood_Urea",
    "Creatinina sérica": "Serum_Creatinine",
    "Sodio en sangre": "Sodium",
    "Potasio en sangre": "Potassium",
    "Hemoglobina": "Hemoglobin",
    "Volumen corpuscular empaquetado": "Packed_Cell_Volume",
    "Recuento de glóbulos blancos": "White_Blood_Cell_Count",
    "Recuento de glóbulos rojos": "Red_Blood_Cell_Count",
    "Apetito": "Appetite",
    "Insuficiencia renal crónica": "Chronic_Kidney_Disease"
})

In [9]:
identifier_columns = ["Patient_ID","Age"]

numerical_columns = ["Age","Blood_Pressure", "Specific_Gravity", "Albumin", "Sugar", "Blood_Glucose_Random",
       "Blood_Urea", "Serum_Creatinine", "Sodium", "Potassium", "Hemoglobin", "Packed_Cell_Volume",
       "White_Blood_Cell_Count", "Red_Blood_Cell_Count"] 

category_columns = ["Red_Blood_Cells", "Pus_Cells", "Pus_Cell_Clumps", "Bacteria", "Appetite"]

target_column = "Chronic_Kidney_Disease"

In [10]:
print(df.describe().T.round(2))

                          count     mean      std     min      25%     50%       75%      max
Patient_ID              15051.0  7525.00  4344.99     0.0  3762.50  7525.0  11287.50  15050.0
Age                     15051.0    52.10    17.55     2.0    45.00    55.0     65.00     90.0
Blood_Pressure          15051.0    93.23    19.91    50.0    80.00    94.0    107.00    180.0
Specific_Gravity        15051.0   541.34   502.98    10.0    12.63  1015.0   1020.00   1025.0
Albumin                 15051.0   228.36   314.22     0.0     0.00     1.0    452.40    989.9
Sugar                   15051.0   154.32   248.58     0.0     0.00     1.0    200.00   1000.0
Blood_Glucose_Random    15051.0   157.61    62.35    70.0   105.00   139.0    208.00    300.0
Blood_Urea              15051.0    59.65    42.51    10.0    25.00    40.0     93.55    200.0
Serum_Creatinine        15042.0     3.22     5.48     0.4     0.93     1.4      3.25     76.0
Sodium                  15051.0   138.58     5.82   120.0   135.00   139.0    143.00    150.0
Potassium               15051.0     5.38     0.86     3.5     4.79     5.4      6.09      7.5
Hemoglobin              15051.0    12.00     2.41     6.0    10.00    12.0     14.00     16.0
Packed_Cell_Volume      15051.0    36.84     7.39    20.0    30.50    36.0     43.00     50.0
White_Blood_Cell_Count  15051.0  7624.35  2250.21  3044.0  5691.00  7628.0   9505.00  11999.0
Red_Blood_Cell_Count    15051.0     4.38     1.02     2.5     3.50     4.5      5.30      6.0

In [11]:
print(df.describe(include='string').T)

                        count unique      top   freq
Red_Blood_Cells         15051      2   normal   7690
Pus_Cells               15051      2   normal   7655
Pus_Cell_Clumps         15042      2  ausente  12596
Bacteria                15045      2  ausente  13732
Appetite                15050      2    bueno   8425
Chronic_Kidney_Disease  15049      2       no   7696

In [12]:

print("Values of categorical columns")
for column in category_columns:
    print(df[column].unique())
    

print("Count of unique values in categorical columns")
for column in category_columns:
    print(df[column].value_counts(dropna=False))

Values of categorical columns
<StringArray>
['anormal', 'normal']
Length: 2, dtype: str
<StringArray>
['anormal', 'normal']
Length: 2, dtype: str
<StringArray>
['presente', 'ausente', nan]
Length: 3, dtype: str
<StringArray>
['presente', 'ausente', nan]
Length: 3, dtype: str
<StringArray>
['bajo', 'bueno', nan]
Length: 3, dtype: str
Count of unique values in categorical columns
Red_Blood_Cells
normal     7690
anormal    7361
Name: count, dtype: int64
Pus_Cells
normal     7655
anormal    7396
Name: count, dtype: int64
Pus_Cell_Clumps
ausente     12596
presente     2446
NaN             9
Name: count, dtype: int64
Bacteria
ausente     13732
presente     1313
NaN             6
Name: count, dtype: int64
Appetite
bueno    8425
bajo     6625
NaN         1
Name: count, dtype: int64

In [13]:
print("target_column", df[target_column].value_counts(dropna=False))

target_column Chronic_Kidney_Disease
no     7696
si     7353
NaN       2
Name: count, dtype: int64

In [14]:
display(df.isna().sum())

Patient_ID                0
Age                       0
Blood_Pressure            0
Specific_Gravity          0
Albumin                   0
Sugar                     0
Red_Blood_Cells           0
Pus_Cells                 0
Pus_Cell_Clumps           9
Bacteria                  6
Blood_Glucose_Random      0
Blood_Urea                0
Serum_Creatinine          9
Sodium                    0
Potassium                 0
Hemoglobin                0
Packed_Cell_Volume        0
White_Blood_Cell_Count    0
Red_Blood_Cell_Count      0
Appetite                  1
Chronic_Kidney_Disease    2
dtype: int64

In [15]:
for column in numerical_columns:
    print(df[column].agg(["min", "max"]))

min     2
max    90
Name: Age, dtype: int64
min     50
max    180
Name: Blood_Pressure, dtype: int64
min      10.0
max    1025.0
Name: Specific_Gravity, dtype: float64
min      0.0
max    989.9
Name: Albumin, dtype: float64
min       0
max    1000
Name: Sugar, dtype: int64
min     70
max    300
Name: Blood_Glucose_Random, dtype: int64
min     10.0
max    200.0
Name: Blood_Urea, dtype: float64
min     0.4
max    76.0
Name: Serum_Creatinine, dtype: float64
min    120.0
max    150.0
Name: Sodium, dtype: float64
min    3.5
max    7.5
Name: Potassium, dtype: float64
min     6.0
max    16.0
Name: Hemoglobin, dtype: float64
min    20.0
max    50.0
Name: Packed_Cell_Volume, dtype: float64
min     3044
max    11999
Name: White_Blood_Cell_Count, dtype: int64
min    2.5
max    6.0
Name: Red_Blood_Cell_Count, dtype: float64

In [16]:
older_than_40 = df["Age"] > 40

display(df.loc[older_than_40, ["Age", "Blood_Pressure"]].head())

   Age  Blood_Pressure
0   48             178
2   62             165
3   48             141
4   51             175
5   60             156

In [17]:
mask = (df["Age"] >= 30) & (df["Blood_Pressure"] > 80)

display(df.loc[mask, ["Age", "Blood_Pressure"]].head())

   Age  Blood_Pressure
0   48             178
2   62             165
3   48             141
4   51             175
5   60             156

In [18]:
mask = ~(df["Age"] > 40)

display(df.loc[mask, ["Age"]].head())

    Age
1     7
7    24
15   40
23   21
30   40

In [20]:
print('known Chronic_Kidney_Disease rows:', df['Chronic_Kidney_Disease'].notna().sum())

known Chronic_Kidney_Disease rows: 15049

In [22]:
missing_percentage = df.isna().mean() * 100
print(missing_percentage.sort_values(ascending=False))

Pus_Cell_Clumps           0.059797
Serum_Creatinine          0.059797
Bacteria                  0.039864
Chronic_Kidney_Disease    0.013288
Appetite                  0.006644
Albumin                   0.000000
Specific_Gravity          0.000000
Blood_Pressure            0.000000
Age                       0.000000
Patient_ID                0.000000
Red_Blood_Cells           0.000000
Pus_Cells                 0.000000
Sugar                     0.000000
Blood_Urea                0.000000
Blood_Glucose_Random      0.000000
Sodium                    0.000000
Potassium                 0.000000
Packed_Cell_Volume        0.000000
Hemoglobin                0.000000
Red_Blood_Cell_Count      0.000000
White_Blood_Cell_Count    0.000000
dtype: float64

In [23]:
print("duplicate rows:", df.duplicated().sum())

duplicate rows: 0