In [8]:
import pandas as pd
import numpy as np
from pathlib import Path
from IPython.display import display
import matplotlib.pyplot as plt
import seaborn as sns
import csv
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)
import sys
np.set_printoptions(threshold=sys.maxsize)
from IPython.display import display

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", lambda x: f"{x:.2f}")

df = pd.read_csv(
    "Covid Data.csv",
    sep=",",
    engine="python",
    quoting=csv.QUOTE_MINIMAL
)

df_clean = df.copy(deep=True)

In [30]:
df_clean["DATE_DIED_original"] = df_clean["DATE_DIED"].copy()

df_clean["NO_DEATH_DATE"] = df_clean["DATE_DIED"].eq("9999-99-99")

df_clean["DATE_DIED"] = pd.to_datetime(
    df_clean["DATE_DIED"].replace("9999-99-99", pd.NA),
    format="%d/%m/%Y",
    errors="coerce"
)

print("New DATE_DIED dtype:", df_clean["DATE_DIED"].dtype)
print("Missing dates:", df_clean["DATE_DIED"].isna().sum())
print("No-death-date marker:", df_clean["NO_DEATH_DATE"].sum())
print("Unparsed dates:",
      (df_clean["DATE_DIED"].isna() & ~df_clean["NO_DEATH_DATE"]).sum())

New DATE_DIED dtype: datetime64[us]
Missing dates: 971633
No-death-date marker: 971633
Unparsed dates: 0

In [5]:
for col in ["INTUBED", "ICU", "PREGNANT", "PNEUMONIA", "DIABETES"]:
    from IPython.display import display
    print(df_clean[col].value_counts(dropna=False).sort_index())

INTUBED
1      33656
2     159050
97    848544
99      7325
Name: count, dtype: int64
ICU
1      16858
2     175685
97    848544
99      7488
Name: count, dtype: int64
PREGNANT
1       8131
2     513179
97    523511
98      3754
Name: count, dtype: int64
PNEUMONIA
1     140038
2     892534
99     16003
Name: count, dtype: int64
DIABETES
1     124989
2     920248
98      3338
Name: count, dtype: int64

In [6]:
cols_to_review = [
    "INTUBED", "ICU", "PREGNANT", "PNEUMONIA",
    "DIABETES", "COPD", "ASTHMA", "INMSUPR",
    "HIPERTENSION", "OTHER_DISEASE", "CARDIOVASCULAR",
    "OBESITY", "RENAL_CHRONIC", "TOBACCO"
]

for col in cols_to_review:
    backup_col = f"{col}_original"
    if backup_col not in df_clean.columns:
        df_clean[backup_col] = df_clean[col].copy()

print("Original category codes preserved.")
print("Working dataset shape:", df_clean.shape)

Original category codes preserved.
Working dataset shape: (1048575, 35)

In [14]:

special_codes = {
    "INTUBED": [97, 99],
    "ICU": [97, 99],
    "PREGNANT": [97, 98],
    "PNEUMONIA": [99],
    "DIABETES": [98],
    "COPD": [98],
    "ASTHMA": [98],
    "INMSUPR": [98],
    "HIPERTENSION": [98],
    "OTHER_DISEASE": [98],
    "CARDIOVASCULAR": [98],
    "OBESITY": [98],
    "RENAL_CHRONIC": [98],
    "TOBACCO": [98]
}

for col, codes in special_codes.items():
    display(col)
    for code in codes:
        count = (df_clean[col] == code).sum()
        display(f"Code {code}: {count}")

'INTUBED'

'Code 97: 848544'

'Code 99: 7325'

'ICU'

'Code 97: 848544'

'Code 99: 7488'

'PREGNANT'

'Code 97: 523511'

'Code 98: 3754'

'PNEUMONIA'

'Code 99: 16003'

'DIABETES'

'Code 98: 3338'

'COPD'

'Code 98: 3003'

'ASTHMA'

'Code 98: 2979'

'INMSUPR'

'Code 98: 3404'

'HIPERTENSION'

'Code 98: 3104'

'OTHER_DISEASE'

'Code 98: 5045'

'CARDIOVASCULAR'

'Code 98: 3076'

'OBESITY'

'Code 98: 3032'

'RENAL_CHRONIC'

'Code 98: 3006'

'TOBACCO'

'Code 98: 3220'

In [15]:
df_clean["INTUBED_NOT_APPLICABLE"] = df_clean["INTUBED"].eq(97)
df_clean["ICU_NOT_APPLICABLE"] = df_clean["ICU"].eq(97)
df_clean["PREGNANT_NOT_APPLICABLE"] = df_clean["PREGNANT"].eq(97)

print("INTUBED not applicable:",
      df_clean["INTUBED_NOT_APPLICABLE"].sum())
print("ICU not applicable:",
      df_clean["ICU_NOT_APPLICABLE"].sum())
print("PREGNANT not applicable:",
      df_clean["PREGNANT_NOT_APPLICABLE"].sum())

INTUBED not applicable: 848544
ICU not applicable: 848544
PREGNANT not applicable: 523511

In [16]:

special_codes = {
    "INTUBED": [97, 99],
    "ICU": [97, 99],
    "PREGNANT": [97, 98],
    "PNEUMONIA": [99],
    "DIABETES": [98],
    "COPD": [98],
    "ASTHMA": [98],
    "INMSUPR": [98],
    "HIPERTENSION": [98],
    "OTHER_DISEASE": [98],
    "CARDIOVASCULAR": [98],
    "OBESITY": [98],
    "RENAL_CHRONIC": [98],
    "TOBACCO": [98]
}

for col, codes in special_codes.items():
    print(f"\n{col}")
    display(df_clean[col].value_counts().sort_index().to_dict())

INTUBED

{1: 33656, 2: 159050, 97: 848544, 99: 7325}

ICU

{1: 16858, 2: 175685, 97: 848544, 99: 7488}

PREGNANT

{1: 8131, 2: 513179, 97: 523511, 98: 3754}

PNEUMONIA

{1: 140038, 2: 892534, 99: 16003}

DIABETES

{1: 124989, 2: 920248, 98: 3338}

COPD

{1: 15062, 2: 1030510, 98: 3003}

ASTHMA

{1: 31572, 2: 1014024, 98: 2979}

INMSUPR

{1: 14170, 2: 1031001, 98: 3404}

HIPERTENSION

{1: 162729, 2: 882742, 98: 3104}

OTHER_DISEASE

{1: 28040, 2: 1015490, 98: 5045}

CARDIOVASCULAR

{1: 20769, 2: 1024730, 98: 3076}

OBESITY

{1: 159816, 2: 885727, 98: 3032}

RENAL_CHRONIC

{1: 18904, 2: 1026665, 98: 3006}

TOBACCO

{1: 84376, 2: 960979, 98: 3220}

In [17]:
special_codes = {
    "INTUBED": [97, 99],
    "ICU": [97, 99],
    "PREGNANT": [97, 98],
    "PNEUMONIA": [99],
    "DIABETES": [98],
    "COPD": [98],
    "ASTHMA": [98],
    "INMSUPR": [98],
    "HIPERTENSION": [98],
    "OTHER_DISEASE": [98],
    "CARDIOVASCULAR": [98],
    "OBESITY": [98],
    "RENAL_CHRONIC": [98],
    "TOBACCO": [98]
}


for col, codes in special_codes.items():
    df_clean[f"{col}_NOT_APPLICABLE"] = df_clean[col].eq(97)
    df_clean[f"{col}_UNKNOWN"] = df_clean[col].isin([98, 99])


for col, codes in special_codes.items():
    df_clean[col] = df_clean[col].mask(
        df_clean[col].isin(codes), pd.NA
    ).astype("Int64")


print("Dataset shape:", df_clean.shape)

for col in special_codes:
    print(
        col,
        "| Missing:", df_clean[col].isna().sum(),
        "| Remaining values:",
        sorted(df_clean[col].dropna().unique().tolist())
    )

Dataset shape: (1048575, 63)
INTUBED | Missing: 855869 | Remaining values: [1, 2]
ICU | Missing: 856032 | Remaining values: [1, 2]
PREGNANT | Missing: 527265 | Remaining values: [1, 2]
PNEUMONIA | Missing: 16003 | Remaining values: [1, 2]
DIABETES | Missing: 3338 | Remaining values: [1, 2]
COPD | Missing: 3003 | Remaining values: [1, 2]
ASTHMA | Missing: 2979 | Remaining values: [1, 2]
INMSUPR | Missing: 3404 | Remaining values: [1, 2]
HIPERTENSION | Missing: 3104 | Remaining values: [1, 2]
OTHER_DISEASE | Missing: 5045 | Remaining values: [1, 2]
CARDIOVASCULAR | Missing: 3076 | Remaining values: [1, 2]
OBESITY | Missing: 3032 | Remaining values: [1, 2]
RENAL_CHRONIC | Missing: 3006 | Remaining values: [1, 2]
TOBACCO | Missing: 3220 | Remaining values: [1, 2]

In [18]:

for col in ["INTUBED", "ICU", "PREGNANT", "PNEUMONIA", "DIABETES"]:
    print(f"\n{col}")
    print("Not applicable:", df_clean[f"{col}_NOT_APPLICABLE"].sum())
    print("Unknown:", df_clean[f"{col}_UNKNOWN"].sum())

INTUBED
Not applicable: 848544
Unknown: 7325

ICU
Not applicable: 848544
Unknown: 7488

PREGNANT
Not applicable: 523511
Unknown: 3754

PNEUMONIA
Not applicable: 0
Unknown: 16003

DIABETES
Not applicable: 0
Unknown: 3338

In [19]:
for col in special_codes:
    print(
        col,
        "Remaining special codes:",
        df_clean[col].isin([97, 98, 99]).sum()
    )

INTUBED Remaining special codes: 0
ICU Remaining special codes: 0
PREGNANT Remaining special codes: 0
PNEUMONIA Remaining special codes: 0
DIABETES Remaining special codes: 0
COPD Remaining special codes: 0
ASTHMA Remaining special codes: 0
INMSUPR Remaining special codes: 0
HIPERTENSION Remaining special codes: 0
OTHER_DISEASE Remaining special codes: 0
CARDIOVASCULAR Remaining special codes: 0
OBESITY Remaining special codes: 0
RENAL_CHRONIC Remaining special codes: 0
TOBACCO Remaining special codes: 0

In [22]:
categorical_cols = [
    "SEX",
    "PATIENT_TYPE",
    "USMER",
    "MEDICAL_UNIT",
    "CLASIFFICATION_FINAL"
]

for col in categorical_cols:
    display(df_clean[col].value_counts(dropna=False).sort_index())

SEX
1    525064
2    523511
Name: count, dtype: int64

PATIENT_TYPE
1    848544
2    200031
Name: count, dtype: int64

USMER
1    385672
2    662903
Name: count, dtype: int64

MEDICAL_UNIT
1        151
2        169
3      19175
4     314405
5       7244
6      40584
7        891
8      10399
9      38116
10      7873
11      5577
12    602995
13       996
Name: count, dtype: int64

CLASIFFICATION_FINAL
1      8601
2      1851
3    381527
4      3122
5     26091
6    128133
7    499250
Name: count, dtype: int64

In [23]:
numeric_cols = ["AGE"]
date_cols = ["DATE_DIED"]


print("=== DESCRIPTIVE STATISTICS ===")
display(df_clean[numeric_cols].describe().T)

outlier_summary = []

for col in numeric_cols:
    s = pd.to_numeric(df_clean[col], errors="coerce").dropna()

    Q1 = s.quantile(0.25)
    Q2 = s.quantile(0.50)
    Q3 = s.quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outlier_summary.append({
        "Column": col,
        "Q1": Q1,
        "Median (Q2)": Q2,
        "Q3": Q3,
        "IQR": IQR,
        "Lower Bound": lower_bound,
        "Upper Bound": upper_bound,
        "Below Lower Bound": (s < lower_bound).sum(),
        "Above Upper Bound": (s > upper_bound).sum(),
        "Total Outliers": (
            (s < lower_bound) | (s > upper_bound)
        ).sum()
    })

outlier_summary = pd.DataFrame(outlier_summary)

print("\n=== QUARTILES, IQR & OUTLIERS ===")
display(outlier_summary)

=== DESCRIPTIVE STATISTICS ===

         count  mean   std  min   25%   50%   75%    max
AGE 1048575.00 41.79 16.91 0.00 30.00 40.00 53.00 121.00

=== QUARTILES, IQR & OUTLIERS ===

,Column,Q1,Median (Q2),Q3,IQR,Lower Bound,Upper Bound,Below Lower Bound,Above Upper Bound,Total Outliers
0,AGE,30.00,40.00,53.00,23.00,-4.50,87.50,0,5640,5640

In [24]:
age_outliers = df_clean.loc[df_clean["AGE"] > 87.5, "AGE"]

print("Number of age outliers:", len(age_outliers))

print("\nAge frequencies:")
display(age_outliers.value_counts().sort_index().to_frame("Count"))

print("\nSelected percentiles:")
display(
    df_clean["AGE"].quantile(
        [0.90, 0.95, 0.99, 0.995, 0.999]
    ).to_frame("AGE")
)

print("\nRecords with age above 100:")
display(
    df_clean.loc[df_clean["AGE"] > 100, ["AGE"]]
    .value_counts()
    .sort_index()
    .to_frame("Count")
)

Number of age outliers: 5640

Age frequencies:

     Count
AGE
88    1093
89     924
90     903
91     595
92     449
93     376
94     281
95     271
96     195
97     135
98     124
99      86
100     70
101     25
102     21
103     19
104     15
105      7
106      4
107      5
108      8
109      6
110      6
111      1
113      1
114      2
115      2
116      2
117      3
118      2
119      3
120      5
121      1

Selected percentiles:

       AGE
0.90 64.00
0.95 72.00
0.99 84.00
0.99 88.00
1.00 94.00

Records with age above 100:

     Count
AGE
101     25
102     21
103     19
104     15
105      7
106      4
107      5
108      8
109      6
110      6
111      1
113      1
114      2
115      2
116      2
117      3
118      2
119      3
120      5
121      1

In [25]:
checks = {
    "AGE below 0": df_clean["AGE"] < 0,
    "AGE above 100": df_clean["AGE"] > 100,

    "SEX invalid": ~df_clean["SEX"].isin([1, 2]),
    "PATIENT_TYPE invalid": ~df_clean["PATIENT_TYPE"].isin([1, 2]),
    "USMER invalid": ~df_clean["USMER"].isin([1, 2]),
    "MEDICAL_UNIT invalid": ~df_clean["MEDICAL_UNIT"].isin(range(1, 14)),
    "CLASIFFICATION_FINAL invalid":
        ~df_clean["CLASIFFICATION_FINAL"].isin(range(1, 8)),

    "INTUBED invalid":
        df_clean["INTUBED"].notna() & ~df_clean["INTUBED"].isin([1, 2]),
    "ICU invalid":
        df_clean["ICU"].notna() & ~df_clean["ICU"].isin([1, 2]),
    "PREGNANT invalid":
        df_clean["PREGNANT"].notna() & ~df_clean["PREGNANT"].isin([1, 2]),

    "PNEUMONIA invalid":
        df_clean["PNEUMONIA"].notna() & ~df_clean["PNEUMONIA"].isin([1, 2]),
    "DIABETES invalid":
        df_clean["DIABETES"].notna() & ~df_clean["DIABETES"].isin([1, 2]),
    "COPD invalid":
        df_clean["COPD"].notna() & ~df_clean["COPD"].isin([1, 2]),
    "ASTHMA invalid":
        df_clean["ASTHMA"].notna() & ~df_clean["ASTHMA"].isin([1, 2]),
    "INMSUPR invalid":
        df_clean["INMSUPR"].notna() & ~df_clean["INMSUPR"].isin([1, 2]),
    "HIPERTENSION invalid":
        df_clean["HIPERTENSION"].notna() & ~df_clean["HIPERTENSION"].isin([1, 2]),
    "OTHER_DISEASE invalid":
        df_clean["OTHER_DISEASE"].notna() & ~df_clean["OTHER_DISEASE"].isin([1, 2]),
    "CARDIOVASCULAR invalid":
        df_clean["CARDIOVASCULAR"].notna() & ~df_clean["CARDIOVASCULAR"].isin([1, 2]),
    "OBESITY invalid":
        df_clean["OBESITY"].notna() & ~df_clean["OBESITY"].isin([1, 2]),
    "RENAL_CHRONIC invalid":
        df_clean["RENAL_CHRONIC"].notna() & ~df_clean["RENAL_CHRONIC"].isin([1, 2]),
    "TOBACCO invalid":
        df_clean["TOBACCO"].notna() & ~df_clean["TOBACCO"].isin([1, 2]),
}

logical_report = pd.DataFrame({
    "Check": checks.keys(),
    "Problematic records": [int(mask.sum()) for mask in checks.values()]
})

display(logical_report)

                           Check  Problematic records
0                    AGE below 0                    0
1                  AGE above 100                  138
2                    SEX invalid                    0
3           PATIENT_TYPE invalid                    0
4                  USMER invalid                    0
5           MEDICAL_UNIT invalid                    0
6   CLASIFFICATION_FINAL invalid                    0
7                INTUBED invalid                    0
8                    ICU invalid                    0
9               PREGNANT invalid                    0
10             PNEUMONIA invalid                    0
11              DIABETES invalid                    0
12                  COPD invalid                    0
13                ASTHMA invalid                    0
14               INMSUPR invalid                    0
15          HIPERTENSION invalid                    0
16         OTHER_DISEASE invalid                    0
17        CARDIOVASCULAR invalid                    0
18               OBESITY invalid                    0
19         RENAL_CHRONIC invalid                    0
20               TOBACCO invalid                    0

In [31]:
print("DATE_DIED dtype:", df_clean["DATE_DIED"].dtype)

print(
    "Missing DATE_DIED:",
    df_clean["DATE_DIED"].isna().sum()
)

print(
    "NO_DEATH_DATE counts:"
)
print(df_clean["NO_DEATH_DATE"].value_counts(dropna=False))

print(
    "\nValid death dates:",
    df_clean["DATE_DIED"].notna().sum()
)

print(
    "\nEarliest death date:",
    df_clean["DATE_DIED"].min()
)

print(
    "Latest death date:",
    df_clean["DATE_DIED"].max()
)

print(
    "\nMissing dates where NO_DEATH_DATE is False:",
    (
        df_clean["DATE_DIED"].isna()
        & ~df_clean["NO_DEATH_DATE"]
    ).sum()
)

print(
    "Dates present where NO_DEATH_DATE is True:",
    (
        df_clean["DATE_DIED"].notna()
        & df_clean["NO_DEATH_DATE"]
    ).sum()
)

DATE_DIED dtype: datetime64[us]
Missing DATE_DIED: 971633
NO_DEATH_DATE counts:
NO_DEATH_DATE
True     971633
False     76942
Name: count, dtype: int64

Valid death dates: 76942

Earliest death date: 2020-01-02 00:00:00
Latest death date: 2021-05-02 00:00:00

Missing dates where NO_DEATH_DATE is False: 0
Dates present where NO_DEATH_DATE is True: 0

In [32]:
df_clean["HAS_DEATH_DATE"] = df_clean["DATE_DIED"].notna()

death_classification = pd.crosstab(
    df_clean["HAS_DEATH_DATE"],
    df_clean["CLASIFFICATION_FINAL"],
    margins=True
)

print("Death date vs classification:")
display(death_classification)

print("\nRow percentages:")
display(
    pd.crosstab(
        df_clean["HAS_DEATH_DATE"],
        df_clean["CLASIFFICATION_FINAL"],
        normalize="index"
    ).round(4) * 100
)

Death date vs classification:

CLASIFFICATION_FINAL     1     2       3     4      5       6       7      All
HAS_DEATH_DATE
False                 7646     0  330097  2974  24880  120481  485555   971633
True                   955  1851   51430   148   1211    7652   13695    76942
All                   8601  1851  381527  3122  26091  128133  499250  1048575

Row percentages:

CLASIFFICATION_FINAL    1    2     3    4    5     6     7
HAS_DEATH_DATE
False                0.79 0.00 33.97 0.31 2.56 12.40 49.97
True                 1.24 2.41 66.84 0.19 1.57  9.95 17.80

In [33]:
print("PATIENT_TYPE vs INTUBED")
display(pd.crosstab(
    df_clean["PATIENT_TYPE"],
    df_clean["INTUBED"],
    margins=True,
    dropna=False
))

print("\nPATIENT_TYPE vs ICU")
display(pd.crosstab(
    df_clean["PATIENT_TYPE"],
    df_clean["ICU"],
    margins=True,
    dropna=False
))

print("\nSEX vs PREGNANT")
display(pd.crosstab(
    df_clean["SEX"],
    df_clean["PREGNANT"],
    margins=True,
    dropna=False
))

PATIENT_TYPE vs INTUBED

INTUBED           1       2     NaN      All
PATIENT_TYPE
1                 0       0  848544   848544
2             33656  159050    7325   200031
All           33656  159050  855869  1048575

PATIENT_TYPE vs ICU

ICU               1       2     NaN      All
PATIENT_TYPE
1                 0       0  848544   848544
2             16858  175685    7488   200031
All           16858  175685  856032  1048575

SEX vs PREGNANT

PREGNANT     1       2     NaN      All
SEX
1         8131  513179    3754   525064
2            0       0  523511   523511
All       8131  513179  527265  1048575

In [35]:

missing_report = pd.DataFrame({
    "Missing_Count": df_clean.isna().sum(),
    "Missing_Percentage": (
        df_clean.isna().mean() * 100
    ).round(2)
})

missing_report = missing_report[
    missing_report["Missing_Count"] > 0
].sort_values(
    "Missing_Percentage",
    ascending=False
)

display(missing_report)

                Missing_Count  Missing_Percentage
DATE_DIED              971633               92.66
ICU                    856032               81.64
INTUBED                855869               81.62
PREGNANT               527265               50.28
PNEUMONIA               16003                1.53
OTHER_DISEASE            5045                0.48
DIABETES                 3338                0.32
INMSUPR                  3404                0.32
TOBACCO                  3220                0.31
HIPERTENSION             3104                0.30
COPD                     3003                0.29
RENAL_CHRONIC            3006                0.29
CARDIOVASCULAR           3076                0.29
OBESITY                  3032                0.29
ASTHMA                   2979                0.28

In [34]:
df_clean.to_csv("covid_cleaned.csv", index=False)