In [32]:
import pandas as pd
import numpy as np
from pathlib import Path
from IPython.display import display
import matplotlib.pyplot as plt
import seaborn as sns
import csv
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)
import sys
np.set_printoptions(threshold=sys.maxsize)

In [3]:
pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", lambda x: f"{x:.2f}")

df = pd.read_csv(
    "Covid Data.csv",
    sep=",",
    engine="python",
    quoting=csv.QUOTE_MINIMAL
)

print("Dataset Shape:", df.shape)

display(df.head())

print(df.columns.tolist())

display(df.dtypes.to_frame("dtype"))

print(df.memory_usage(deep=True).sum() / 1024, "KB")

df.info()

display(df.describe().T)

Dataset Shape: (1048575, 21)

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,DATE_DIED,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,COPD,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU
0,2,1,1,1,03/05/2020,97,1,65,2,2,2,2,2,1,2,2,2,2,2,3,97
1,2,1,2,1,03/06/2020,97,1,72,97,2,2,2,2,1,2,2,1,1,2,5,97
2,2,1,2,2,09/06/2020,1,2,55,97,1,2,2,2,2,2,2,2,2,2,3,2
3,2,1,1,1,12/06/2020,97,2,53,2,2,2,2,2,2,2,2,2,2,2,7,97
4,2,1,2,1,21/06/2020,97,2,68,97,1,2,2,2,1,2,2,2,2,2,3,97

['USMER', 'MEDICAL_UNIT', 'SEX', 'PATIENT_TYPE', 'DATE_DIED', 'INTUBED', 'PNEUMONIA', 'AGE', 'PREGNANT', 'DIABETES', 'COPD', 'ASTHMA', 'INMSUPR', 'HIPERTENSION', 'OTHER_DISEASE', 'CARDIOVASCULAR', 'OBESITY', 'RENAL_CHRONIC', 'TOBACCO', 'CLASIFFICATION_FINAL', 'ICU']

                      dtype
USMER                 int64
MEDICAL_UNIT          int64
SEX                   int64
PATIENT_TYPE          int64
DATE_DIED               str
INTUBED               int64
PNEUMONIA             int64
AGE                   int64
PREGNANT              int64
DIABETES              int64
COPD                  int64
ASTHMA                int64
INMSUPR               int64
HIPERTENSION          int64
OTHER_DISEASE         int64
CARDIOVASCULAR        int64
OBESITY               int64
RENAL_CHRONIC         int64
TOBACCO               int64
CLASIFFICATION_FINAL  int64
ICU                   int64

224255.9150390625 KB
<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 21 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   USMER                 1048575 non-null  int64
 1   MEDICAL_UNIT          1048575 non-null  int64
 2   SEX                   1048575 non-null  int64
 3   PATIENT_TYPE          1048575 non-null  int64
 4   DATE_DIED             1048575 non-null  str
 5   INTUBED               1048575 non-null  int64
 6   PNEUMONIA             1048575 non-null  int64
 7   AGE                   1048575 non-null  int64
 8   PREGNANT              1048575 non-null  int64
 9   DIABETES              1048575 non-null  int64
 10  COPD                  1048575 non-null  int64
 11  ASTHMA                1048575 non-null  int64
 12  INMSUPR               1048575 non-null  int64
 13  HIPERTENSION          1048575 non-null  int64
 14  OTHER_DISEASE         1048575 non-null  int64
 15  CARDIOVASCULAR        1048575 non-null  int64
 16  OBESITY               1048575 non-null  int64
 17  RENAL_CHRONIC         1048575 non-null  int64
 18  TOBACCO               1048575 non-null  int64
 19  CLASIFFICATION_FINAL  1048575 non-null  int64
 20  ICU                   1048575 non-null  int64
dtypes: int64(20), str(1)
memory usage: 168.0 MB

                          count  mean   std  min   25%   50%   75%    max
USMER                1048575.00  1.63  0.48 1.00  1.00  2.00  2.00   2.00
MEDICAL_UNIT         1048575.00  8.98  3.72 1.00  4.00 12.00 12.00  13.00
SEX                  1048575.00  1.50  0.50 1.00  1.00  1.00  2.00   2.00
PATIENT_TYPE         1048575.00  1.19  0.39 1.00  1.00  1.00  1.00   2.00
INTUBED              1048575.00 79.52 36.87 1.00 97.00 97.00 97.00  99.00
PNEUMONIA            1048575.00  3.35 11.91 1.00  2.00  2.00  2.00  99.00
AGE                  1048575.00 41.79 16.91 0.00 30.00 40.00 53.00 121.00
PREGNANT             1048575.00 49.77 47.51 1.00  2.00 97.00 97.00  98.00
DIABETES             1048575.00  2.19  5.42 1.00  2.00  2.00  2.00  98.00
COPD                 1048575.00  2.26  5.13 1.00  2.00  2.00  2.00  98.00
ASTHMA               1048575.00  2.24  5.11 1.00  2.00  2.00  2.00  98.00
INMSUPR              1048575.00  2.30  5.46 1.00  2.00  2.00  2.00  98.00
HIPERTENSION         1048575.00  2.13  5.24 1.00  2.00  2.00  2.00  98.00
OTHER_DISEASE        1048575.00  2.44  6.65 1.00  2.00  2.00  2.00  98.00
CARDIOVASCULAR       1048575.00  2.26  5.19 1.00  2.00  2.00  2.00  98.00
OBESITY              1048575.00  2.13  5.18 1.00  2.00  2.00  2.00  98.00
RENAL_CHRONIC        1048575.00  2.26  5.14 1.00  2.00  2.00  2.00  98.00
TOBACCO              1048575.00  2.21  5.32 1.00  2.00  2.00  2.00  98.00
CLASIFFICATION_FINAL 1048575.00  5.31  1.88 1.00  3.00  6.00  7.00   7.00
ICU                  1048575.00 79.55 36.82 1.00 97.00 97.00 97.00  99.00

In [8]:
numerical_columns = ["AGE"]


binary_cols = [
    "SEX",
    "PATIENT_TYPE",
    "PNEUMONIA",
    "DIABETES",
    "COPD",
    "ASTHMA",
    "INMSUPR",
    "HIPERTENSION",
    "OTHER_DISEASE",
    "CARDIOVASCULAR",
    "OBESITY",
    "RENAL_CHRONIC",
    "TOBACCO"
]


category_cols = [
    "USMER",
    "MEDICAL_UNIT",
    "CLASIFFICATION_FINAL"
]


date_cols = ["DATE_DIED"]


special_cols = [
    "INTUBED",
    "ICU",
    "PREGNANT"
]

In [9]:
display(df[numerical_columns].describe().T)


for col in binary_cols:
    display(df[col].value_counts(dropna=False).to_frame("Count"))


for col in category_cols:
    display(df[col].value_counts(dropna=False).to_frame("Count"))


for col in special_cols:
    display(df[col].value_counts(dropna=False).to_frame("Count"))


print("\nDATE_DIED sample values:")
display(df["DATE_DIED"].value_counts(dropna=False).head(10))

         count  mean   std  min   25%   50%   75%    max
AGE 1048575.00 41.79 16.91 0.00 30.00 40.00 53.00 121.00

--- SEX ---

      Count
SEX
1    525064
2    523511

--- PATIENT_TYPE ---

               Count
PATIENT_TYPE
1             848544
2             200031

--- PNEUMONIA ---

            Count
PNEUMONIA
2          892534
1          140038
99          16003

--- DIABETES ---

           Count
DIABETES
2         920248
1         124989
98          3338

--- COPD ---

        Count
COPD
2     1030510
1       15062
98       3003

--- ASTHMA ---

          Count
ASTHMA
2       1014024
1         31572
98         2979

--- INMSUPR ---

           Count
INMSUPR
2        1031001
1          14170
98          3404

--- HIPERTENSION ---

               Count
HIPERTENSION
2             882742
1             162729
98              3104

--- OTHER_DISEASE ---

                 Count
OTHER_DISEASE
2              1015490
1                28040
98                5045

--- CARDIOVASCULAR ---

                  Count
CARDIOVASCULAR
2               1024730
1                 20769
98                 3076

--- OBESITY ---

          Count
OBESITY
2        885727
1        159816
98         3032

--- RENAL_CHRONIC ---

                 Count
RENAL_CHRONIC
2              1026665
1                18904
98                3006

--- TOBACCO ---

          Count
TOBACCO
2        960979
1         84376
98         3220

--- USMER ---

        Count
USMER
2      662903
1      385672

--- MEDICAL_UNIT ---

               Count
MEDICAL_UNIT
12            602995
4             314405
6              40584
9              38116
3              19175
8              10399
10              7873
5               7244
11              5577
13               996
7                891
2                169
1                151

--- CLASIFFICATION_FINAL ---

                       Count
CLASIFFICATION_FINAL
7                     499250
3                     381527
6                     128133
5                      26091
1                       8601
4                       3122
2                       1851

--- INTUBED ---

          Count
INTUBED
97       848544
2        159050
1         33656
99         7325

--- ICU ---

      Count
ICU
97   848544
2    175685
1     16858
99     7488

--- PREGNANT ---

           Count
PREGNANT
97        523511
2         513179
1           8131
98          3754

DATE_DIED sample values:

DATE_DIED
9999-99-99    971633
06/07/2020      1000
07/07/2020       996
13/07/2020       990
16/06/2020       979
16/07/2020       938
14/07/2020       935
17/06/2020       926
29/06/2020       925
08/06/2020       923
Name: count, dtype: int64

In [14]:
missing_summary = pd.DataFrame({
    "Missing Count": df.isna().sum(),
    "Missing Percentage": (df.isna().mean() * 100).round(2)
})

display(missing_summary)


special_codes = {
    "PNEUMONIA": [99],
    "INTUBED": [97, 99],
    "ICU": [97, 99],
    "PREGNANT": [97, 98],
    "DIABETES": [98],
    "COPD": [98],
    "ASTHMA": [98],
    "INMSUPR": [98],
    "HIPERTENSION": [98],
    "OTHER_DISEASE": [98],
    "CARDIOVASCULAR": [98],
    "OBESITY": [98],
    "RENAL_CHRONIC": [98],
    "TOBACCO": [98]
}

for col, codes in special_codes.items():
    count = df[col].isin(codes).sum()
    percentage = count / len(df) * 100

    print(
        f"{col}: {count:,} special values "
        f"({percentage:.2f}%)"
    )

print(
    "DATE_DIED = 9999-99-99:",
    (df["DATE_DIED"] == "9999-99-99").sum()
)

                      Missing Count  Missing Percentage
USMER                             0                0.00
MEDICAL_UNIT                      0                0.00
SEX                               0                0.00
PATIENT_TYPE                      0                0.00
DATE_DIED                         0                0.00
INTUBED                           0                0.00
PNEUMONIA                         0                0.00
AGE                               0                0.00
PREGNANT                          0                0.00
DIABETES                          0                0.00
COPD                              0                0.00
ASTHMA                            0                0.00
INMSUPR                           0                0.00
HIPERTENSION                      0                0.00
OTHER_DISEASE                     0                0.00
CARDIOVASCULAR                    0                0.00
OBESITY                           0                0.00
RENAL_CHRONIC                     0                0.00
TOBACCO                           0                0.00
CLASIFFICATION_FINAL              0                0.00
ICU                               0                0.00

PNEUMONIA: 16,003 special values (1.53%)
INTUBED: 855,869 special values (81.62%)
ICU: 856,032 special values (81.64%)
PREGNANT: 527,265 special values (50.28%)
DIABETES: 3,338 special values (0.32%)
COPD: 3,003 special values (0.29%)
ASTHMA: 2,979 special values (0.28%)
INMSUPR: 3,404 special values (0.32%)
HIPERTENSION: 3,104 special values (0.30%)
OTHER_DISEASE: 5,045 special values (0.48%)
CARDIOVASCULAR: 3,076 special values (0.29%)
OBESITY: 3,032 special values (0.29%)
RENAL_CHRONIC: 3,006 special values (0.29%)
TOBACCO: 3,220 special values (0.31%)
DATE_DIED = 9999-99-99: 971633

In [15]:

duplicate_count = df.duplicated().sum()
duplicate_percentage = duplicate_count / len(df) * 100

print("Exact duplicate rows:", duplicate_count)
print("Duplicate percentage:", round(duplicate_percentage, 2), "%")

if duplicate_count > 0:
    display(df[df.duplicated(keep=False)].head(10))

unique_columns = [
    col for col in df.columns
    if df[col].is_unique
]

print("Columns unique across all rows:", unique_columns)

Exact duplicate rows: 812049
Duplicate percentage: 77.44 %

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,DATE_DIED,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,COPD,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU
6,2,1,1,1,9999-99-99,97,2,64,2,2,2,2,2,2,2,2,2,2,2,3,97
19,2,1,1,1,9999-99-99,97,2,64,2,2,2,2,2,2,2,2,2,2,2,3,97
22,2,1,2,1,9999-99-99,97,2,45,97,2,2,2,2,2,2,2,2,2,2,3,97
35,2,1,2,1,9999-99-99,97,2,45,97,2,2,2,2,2,2,2,2,2,2,3,97
49,2,1,1,1,9999-99-99,97,2,30,2,2,2,2,2,2,2,2,2,2,2,7,97
50,2,1,1,1,9999-99-99,97,2,23,2,2,2,2,2,2,2,2,2,2,2,7,97
52,2,1,2,1,9999-99-99,97,2,33,97,2,2,2,2,2,2,2,2,2,2,7,97
59,2,1,1,1,9999-99-99,97,2,28,2,2,2,2,2,2,2,2,2,2,2,7,97
60,2,1,1,2,9999-99-99,2,2,25,2,2,2,2,2,2,2,2,2,2,2,7,2
62,2,1,1,2,9999-99-99,2,2,25,2,2,2,2,2,2,2,2,2,2,2,7,2

Columns unique across all rows: []

The dataset contains 812,049 exact duplicate rows (77.44% of all records). Since no unique patient identifier is available, these duplicates cannot automatically be assumed to represent repeated records of the same patients. Therefore, duplicate removal is postponed until the dataset documentation and record structure are verified. The original dataset is preserved to avoid potentially removing valid observations.

In [16]:
print("Dataset shape:", df.shape)

print("Exact duplicate rows:", df.duplicated().sum())

print("Unique rows:", len(df.drop_duplicates()))

print("Rows duplicated beyond the first occurrence:",
      df.duplicated(keep="first").sum())

Dataset shape: (1048575, 21)
Exact duplicate rows: 812049
Unique rows: 236526
Rows duplicated beyond the first occurrence: 812049

In [18]:
check_cols = ["USMER", "MEDICAL_UNIT", "SEX", "PATIENT_TYPE",
              "DATE_DIED", "AGE", "CLASIFFICATION_FINAL"]

print("\nUnique combinations of selected columns:",
      len(df[check_cols].drop_duplicates()))

print("\nUnique DATE_DIED values:", df["DATE_DIED"].nunique())
print("Unique AGE values:", df["AGE"].nunique())

Unique combinations of selected columns: 80352

Unique DATE_DIED values: 401
Unique AGE values: 121

In [19]:
print("Current dtype:", df["DATE_DIED"].dtype)

print("\nSpecial marker count:")
print((df["DATE_DIED"] == "9999-99-99").sum())

print("\nSample valid-looking date values:")
display(
    df.loc[
        df["DATE_DIED"] != "9999-99-99",
        "DATE_DIED"
    ].head(10)
)

print("\nAGE dtype:", df["AGE"].dtype)
print("Minimum age:", df["AGE"].min())
print("Maximum age:", df["AGE"].max())

Current dtype: str

Special marker count:
971633

Sample valid-looking date values:

0      03/05/2020
1      03/06/2020
2      09/06/2020
3      12/06/2020
4      21/06/2020
151    26/02/2020
152    05/04/2020
153    08/05/2020
154    20/05/2020
155    17/07/2020
Name: DATE_DIED, dtype: str

AGE dtype: int64
Minimum age: 0
Maximum age: 121

In [20]:
df["DATE_DIED_original"] = df["DATE_DIED"].copy()

df["NO_DEATH_DATE"] = df["DATE_DIED"].eq("9999-99-99")

df["DATE_DIED"] = pd.to_datetime(
    df["DATE_DIED"].replace("9999-99-99", pd.NA),
    format="%d/%m/%Y",
    errors="coerce"
)

print("New DATE_DIED dtype:", df["DATE_DIED"].dtype)
print("Missing dates:", df["DATE_DIED"].isna().sum())
print("No-death-date marker:", df["NO_DEATH_DATE"].sum())
print("Unparsed dates:",
      (df["DATE_DIED"].isna() & ~df["NO_DEATH_DATE"]).sum())

New DATE_DIED dtype: datetime64[us]
Missing dates: 971633
No-death-date marker: 971633
Unparsed dates: 0

In [21]:
print(df.dtypes)

USMER                            int64
MEDICAL_UNIT                     int64
SEX                              int64
PATIENT_TYPE                     int64
DATE_DIED               datetime64[us]
INTUBED                          int64
PNEUMONIA                        int64
AGE                              int64
PREGNANT                         int64
DIABETES                         int64
COPD                             int64
ASTHMA                           int64
INMSUPR                          int64
HIPERTENSION                     int64
OTHER_DISEASE                    int64
CARDIOVASCULAR                   int64
OBESITY                          int64
RENAL_CHRONIC                    int64
TOBACCO                          int64
CLASIFFICATION_FINAL             int64
ICU                              int64
DATE_DIED_original                 str
NO_DEATH_DATE                     bool
dtype: object

In [35]:
categorical_cols = [
    "USMER", "MEDICAL_UNIT", "SEX", "PATIENT_TYPE",
    "INTUBED", "PNEUMONIA", "PREGNANT", "DIABETES",
    "COPD", "ASTHMA", "INMSUPR", "HIPERTENSION",
    "OTHER_DISEASE", "CARDIOVASCULAR", "OBESITY",
    "RENAL_CHRONIC", "TOBACCO", "CLASIFFICATION_FINAL",
    "ICU"
]

for col in categorical_cols:
    from IPython.display import display
    display(df[col].value_counts(dropna=False).sort_index())

USMER
1    385672
2    662903
Name: count, dtype: int64

MEDICAL_UNIT
1        151
2        169
3      19175
4     314405
5       7244
6      40584
7        891
8      10399
9      38116
10      7873
11      5577
12    602995
13       996
Name: count, dtype: int64

SEX
1    525064
2    523511
Name: count, dtype: int64

PATIENT_TYPE
1    848544
2    200031
Name: count, dtype: int64

INTUBED
1      33656
2     159050
97    848544
99      7325
Name: count, dtype: int64

PNEUMONIA
1     140038
2     892534
99     16003
Name: count, dtype: int64

PREGNANT
1       8131
2     513179
97    523511
98      3754
Name: count, dtype: int64

DIABETES
1     124989
2     920248
98      3338
Name: count, dtype: int64

COPD
1       15062
2     1030510
98       3003
Name: count, dtype: int64

ASTHMA
1       31572
2     1014024
98       2979
Name: count, dtype: int64

INMSUPR
1       14170
2     1031001
98       3404
Name: count, dtype: int64

HIPERTENSION
1     162729
2     882742
98      3104
Name: count, dtype: int64

OTHER_DISEASE
1       28040
2     1015490
98       5045
Name: count, dtype: int64

CARDIOVASCULAR
1       20769
2     1024730
98       3076
Name: count, dtype: int64

OBESITY
1     159816
2     885727
98      3032
Name: count, dtype: int64

RENAL_CHRONIC
1       18904
2     1026665
98       3006
Name: count, dtype: int64

TOBACCO
1      84376
2     960979
98      3220
Name: count, dtype: int64

CLASIFFICATION_FINAL
1      8601
2      1851
3    381527
4      3122
5     26091
6    128133
7    499250
Name: count, dtype: int64

ICU
1      16858
2     175685
97    848544
99      7488
Name: count, dtype: int64